data=data.replace(/(^|[^A-Za-z])(Bloodstone Fen)(?=[^A-Za-z]|$)/gi, '$1血石沼泽');
data=data.replace(/(^|[^A-Za-z])(The Wilds)(?=[^A-Za-z]|$)/gi, '$1荒原');
data=data.replace(/(^|[^A-Za-z])(Aurora Glade)(?=[^A-Za-z]|$)/gi, '$1欧若拉林地');
data=data.replace(/(^|[^A-Za-z])(Gates of Kryta)(?=[^A-Za-z]|$)/gi, '$1科瑞塔关所');
data=data.replace(/(^|[^A-Za-z])(D'Alessio Seaboard)(?=[^A-Za-z]|$)/gi, '$1达雷西海滨');
data=data.replace(/(^|[^A-Za-z])(Divinity Coast)(?=[^A-Za-z]|$)/gi, '$1神圣海岸');
data=data.replace(/(^|[^A-Za-z])(Sanctum Cay)(?=[^A-Za-z]|$)/gi, '$1神圣沙滩');
data=data.replace(/(^|[^A-Za-z])(Droknar's Forge)(?=[^A-Za-z]|$)/gi, '$1熔炉');
data=data.replace(/(^|[^A-Za-z])(The Frost Gate)(?=[^A-Za-z]|$)/gi, '$1寒霜之门');
data=data.replace(/(^|[^A-Za-z])(Ice Caves of Sorrow)(?=[^A-Za-z]|$)/gi, '$1悲伤冰谷');
data=data.replace(/(^|[^A-Za-z])(Thunderhead Keep)(?=[^A-Za-z]|$)/gi, '$1雷云要塞');
data=data.replace(/(^|[^A-Za-z])(Iron Mines of Moladune)(?=[^A-Za-z]|$)/gi, '$1莫拉登矿山');
data=data.replace(/(^|[^A-Za-z])(Borlis Pass)(?=[^A-Za-z]|$)/gi, '$1柏里斯通道');
data=data.replace(/(^|[^A-Za-z])(The Great Northern Wall)(?=[^A-Za-z]|$)/gi, '$1北方长城');
data=data.replace(/(^|[^A-Za-z])(Fort Ranik)(?=[^A-Za-z]|$)/gi, '$1瑞尼克要塞');
data=data.replace(/(^|[^A-Za-z])(Ruins of Surmia)(?=[^A-Za-z]|$)/gi, '$1蘇米亚废墟');
data=data.replace(/(^|[^A-Za-z])(Nolani Academy)(?=[^A-Za-z]|$)/gi, '$1若拉尼学院');
data=data.replace(/(^|[^A-Za-z])(Ember Light Camp)(?=[^A-Za-z]|$)/gi, '$1残火影地');
data=data.replace(/(^|[^A-Za-z])(Grendich Courthouse)(?=[^A-Za-z]|$)/gi, '$1葛兰迪法院');
data=data.replace(/(^|[^A-Za-z])(Augury Rock)(?=[^A-Za-z]|$)/gi, '$1占卜之石');
data=data.replace(/(^|[^A-Za-z])(Sardelac Sanitarium)(?=[^A-Za-z]|$)/gi, '$1萨德拉克疗养院');
data=data.replace(/(^|[^A-Za-z])(Piken Square)(?=[^A-Za-z]|$)/gi, '$1派肯广场');
data=data.replace(/(^|[^A-Za-z])(Henge of Denravi)(?=[^A-Za-z]|$)/gi, '$1丹拉维圣地');
data=data.replace(/(^|[^A-Za-z])(Senjis Corner)(?=[^A-Za-z]|$)/gi, '$1山吉之街');
data=data.replace(/(^|[^A-Za-z])(Burning Isle)(?=[^A-Za-z]|$)/gi, '$1公会厅 - 燃烧之岛');
data=data.replace(/(^|[^A-Za-z])(Lions Arch)(?=[^A-Za-z]|$)/gi, '$1狮子拱门');
data=data.replace(/(^|[^A-Za-z])(Bergen Hot Springs)(?=[^A-Za-z]|$)/gi, '$1卑而根温泉');
data=data.replace(/(^|[^A-Za-z])(Riverside Province)(?=[^A-Za-z]|$)/gi, '$1河畔地带');
data=data.replace(/(^|[^A-Za-z])(House zu Heltzer)(?=[^A-Za-z]|$)/gi, '$1凤荷议院');
data=data.replace(/(^|[^A-Za-z])(Ascalon City)(?=[^A-Za-z]|$)/gi, '$1阿斯克隆城');
data=data.replace(/(^|[^A-Za-z])(Tomb of the Primeval Kings)(?=[^A-Za-z]|$)/gi, '$1先王之墓');
data=data.replace(/(^|[^A-Za-z])(Ascalon Arena)(?=[^A-Za-z]|$)/gi, '$1竞技场/阿斯克隆');
data=data.replace(/(^|[^A-Za-z])(The Amnoon Oasis)(?=[^A-Za-z]|$)/gi, '$1安奴绿洲');
data=data.replace(/(^|[^A-Za-z])(Dunes of Despair)(?=[^A-Za-z]|$)/gi, '$1绝望沙丘');
data=data.replace(/(^|[^A-Za-z])(Thirsty River)(?=[^A-Za-z]|$)/gi, '$1干枯河流');
data=data.replace(/(^|[^A-Za-z])(Elona Reach)(?=[^A-Za-z]|$)/gi, '$1伊洛那流域');
data=data.replace(/(^|[^A-Za-z])(The Dragon's Lair)(?=[^A-Za-z]|$)/gi, '$1龙穴');
data=data.replace(/(^|[^A-Za-z])(Ring of Fire)(?=[^A-Za-z]|$)/gi, '$1火环群岛');
data=data.replace(/(^|[^A-Za-z])(Abaddon's Mouth)(?=[^A-Za-z]|$)/gi, '$1地狱隘口');
data=data.replace(/(^|[^A-Za-z])(Hell's Precipice)(?=[^A-Za-z]|$)/gi, '$1地狱悬崖');
data=data.replace(/(^|[^A-Za-z])(Lutgardis Conservatory)(?=[^A-Za-z]|$)/gi, '$1路嘉帝斯温室');
data=data.replace(/(^|[^A-Za-z])(Vasburg Armory)(?=[^A-Za-z]|$)/gi, '$1维思柏兵营');
data=data.replace(/(^|[^A-Za-z])(Serenity Temple)(?=[^A-Za-z]|$)/gi, '$1宁静神殿');
data=data.replace(/(^|[^A-Za-z])(Ice Tooth Cave)(?=[^A-Za-z]|$)/gi, '$1冰牙洞穴');
data=data.replace(/(^|[^A-Za-z])(Beacons Perch)(?=[^A-Za-z]|$)/gi, '$1比肯');
data=data.replace(/(^|[^A-Za-z])(Yaks Bend)(?=[^A-Za-z]|$)/gi, '$1犛牛村');
data=data.replace(/(^|[^A-Za-z])(Frontier Gate)(?=[^A-Za-z]|$)/gi, '$1边境关所');
data=data.replace(/(^|[^A-Za-z])(Beetletun)(?=[^A-Za-z]|$)/gi, '$1甲虫镇');
data=data.replace(/(^|[^A-Za-z])(Fishermens Haven)(?=[^A-Za-z]|$)/gi, '$1渔人避风港');
data=data.replace(/(^|[^A-Za-z])(Temple of the Ages)(?=[^A-Za-z]|$)/gi, '$1世纪');
data=data.replace(/(^|[^A-Za-z])(Ventaris Refuge)(?=[^A-Za-z]|$)/gi, '$1凡特里避难所');
data=data.replace(/(^|[^A-Za-z])(Druids Overlook)(?=[^A-Za-z]|$)/gi, '$1德鲁伊高地');
data=data.replace(/(^|[^A-Za-z])(Maguuma Stade)(?=[^A-Za-z]|$)/gi, '$1梅古玛业林');
data=data.replace(/(^|[^A-Za-z])(Quarrel Falls)(?=[^A-Za-z]|$)/gi, '$1怨言瀑布');
data=data.replace(/(^|[^A-Za-z])(Ascalon City)(?=[^A-Za-z]|$)/gi, '$1阿斯克隆城');
data=data.replace(/(^|[^A-Za-z])(Heroes Audience)(?=[^A-Za-z]|$)/gi, '$1英雄之痕');
data=data.replace(/(^|[^A-Za-z])(Seekers Passage)(?=[^A-Za-z]|$)/gi, '$1探索者通道');
data=data.replace(/(^|[^A-Za-z])(Destinys Gorge)(?=[^A-Za-z]|$)/gi, '$1命运峡谷');
data=data.replace(/(^|[^A-Za-z])(Camp Rankor)(?=[^A-Za-z]|$)/gi, '$1蓝口营地');
data=data.replace(/(^|[^A-Za-z])(The Granite Citadel)(?=[^A-Za-z]|$)/gi, '$1花岗岩堡垒');
data=data.replace(/(^|[^A-Za-z])(Marhans Grotto)(?=[^A-Za-z]|$)/gi, '$1马汉');
data=data.replace(/(^|[^A-Za-z])(Port Sledge)(?=[^A-Za-z]|$)/gi, '$1雪橇港');
data=data.replace(/(^|[^A-Za-z])(Copperhammer Mines)(?=[^A-Za-z]|$)/gi, '$1铜锤矿坑');
data=data.replace(/(^|[^A-Za-z])(Pre-Searing: The Barradin Estate)(?=[^A-Za-z]|$)/gi, '$1毁灭前: 巴拉丁领地');
data=data.replace(/(^|[^A-Za-z])(Pre-Searing: Ashford Abbey)(?=[^A-Za-z]|$)/gi, '$1毁灭前: 灰色浅滩');
data=data.replace(/(^|[^A-Za-z])(Pre-Searing: Foibles Fair)(?=[^A-Za-z]|$)/gi, '$1毁灭前: 佛伊伯市集');
data=data.replace(/(^|[^A-Za-z])(Pre-Searing: Fort Ranik)(?=[^A-Za-z]|$)/gi, '$1毁灭前: 瑞尼克要塞');
data=data.replace(/(^|[^A-Za-z])(Shiverpeak Arena)(?=[^A-Za-z]|$)/gi, '$1竞技场/Shiverpeak');
data=data.replace(/(^|[^A-Za-z])(Random Arenas)(?=[^A-Za-z]|$)/gi, '$1随机竞技场');
data=data.replace(/(^|[^A-Za-z])(Team Arenas)(?=[^A-Za-z]|$)/gi, '$1竞技场/Team');
data=data.replace(/(^|[^A-Za-z])(Cavalon)(?=[^A-Za-z]|$)/gi, '$1卡瓦隆');
data=data.replace(/(^|[^A-Za-z])(Kaineng Center)(?=[^A-Za-z]|$)/gi, '$1凯宁中心');
data=data.replace(/(^|[^A-Za-z])(Unwaking Waters - Kurzick)(?=[^A-Za-z]|$)/gi, '$1蓝 - 沉睡之水 - 蓝');
data=data.replace(/(^|[^A-Za-z])(Deldrimor War Camp)(?=[^A-Za-z]|$)/gi, '$1戴而狄摩兵营');
data=data.replace(/(^|[^A-Za-z])(Zen Daijun)(?=[^A-Za-z]|$)/gi, '$1祯台郡');
data=data.replace(/(^|[^A-Za-z])(Minister Chos Estate)(?=[^A-Za-z]|$)/gi, '$1周大臣庄园');
data=data.replace(/(^|[^A-Za-z])(Nahpui Quarter)(?=[^A-Za-z]|$)/gi, '$1纳普区');
data=data.replace(/(^|[^A-Za-z])(Tahnnakai Temple)(?=[^A-Za-z]|$)/gi, '$1谭纳凯神殿');
data=data.replace(/(^|[^A-Za-z])(Arborstone)(?=[^A-Za-z]|$)/gi, '$1亭石');
data=data.replace(/(^|[^A-Za-z])(Boreas Seabed)(?=[^A-Za-z]|$)/gi, '$1风神海床');
data=data.replace(/(^|[^A-Za-z])(Sunjiang District)(?=[^A-Za-z]|$)/gi, '$1孙江行政区');
data=data.replace(/(^|[^A-Za-z])(The Eternal Grove)(?=[^A-Za-z]|$)/gi, '$1永恒之林');
data=data.replace(/(^|[^A-Za-z])(Gyala Hatchery)(?=[^A-Za-z]|$)/gi, '$1盖拉孵化所');
data=data.replace(/(^|[^A-Za-z])(Raisu Palace)(?=[^A-Za-z]|$)/gi, '$1莱蘇皇宫');
data=data.replace(/(^|[^A-Za-z])(Imperial Sanctum)(?=[^A-Za-z]|$)/gi, '$1帝国圣所');
data=data.replace(/(^|[^A-Za-z])(Unwaking Waters Luxon)(?=[^A-Za-z]|$)/gi, '$1红 - 沉睡之水 红');
data=data.replace(/(^|[^A-Za-z])(Amatz Basin)(?=[^A-Za-z]|$)/gi, '$1亚马兹盆地');
data=data.replace(/(^|[^A-Za-z])(The Aurios Mines)(?=[^A-Za-z]|$)/gi, '$1奥里欧斯矿坑');
data=data.replace(/(^|[^A-Za-z])(Shing Jea Monastery)(?=[^A-Za-z]|$)/gi, '$1星岬寺');
data=data.replace(/(^|[^A-Za-z])(Shing Jea Arena)(?=[^A-Za-z]|$)/gi, '$1竞技场/星岬寺');
data=data.replace(/(^|[^A-Za-z])(Great Temple of Balthazar)(?=[^A-Za-z]|$)/gi, '$1巴萨则圣殿');
data=data.replace(/(^|[^A-Za-z])(Tsumei Village)(?=[^A-Za-z]|$)/gi, '$1蘇梅村');
data=data.replace(/(^|[^A-Za-z])(Seitung Harbor)(?=[^A-Za-z]|$)/gi, '$1青函港');
data=data.replace(/(^|[^A-Za-z])(Ran Musu Gardens)(?=[^A-Za-z]|$)/gi, '$1岚穆蘇花园');
data=data.replace(/(^|[^A-Za-z])(Dwayna Vs Grenth)(?=[^A-Za-z]|$)/gi, '$1Dwayna Vs Grenth');
data=data.replace(/(^|[^A-Za-z])(Urgoz's Warren)(?=[^A-Za-z]|$)/gi, '$1尔果');
data=data.replace(/(^|[^A-Za-z])(Altrumm Ruins)(?=[^A-Za-z]|$)/gi, '$1奥楚蘭废墟');
data=data.replace(/(^|[^A-Za-z])(Zos Shivros Channel)(?=[^A-Za-z]|$)/gi, '$1佐席洛斯水道');
data=data.replace(/(^|[^A-Za-z])(Dragons Throat)(?=[^A-Za-z]|$)/gi, '$1龙喉');
data=data.replace(/(^|[^A-Za-z])(Harvest Temple)(?=[^A-Za-z]|$)/gi, '$1丰收神殿');
data=data.replace(/(^|[^A-Za-z])(Breaker Hollow)(?=[^A-Za-z]|$)/gi, '$1断崖谷');
data=data.replace(/(^|[^A-Za-z])(Leviathan Pits)(?=[^A-Za-z]|$)/gi, '$1利拜亚森矿场');
data=data.replace(/(^|[^A-Za-z])(Zaishen Challenge)(?=[^A-Za-z]|$)/gi, '$1战承挑战');
data=data.replace(/(^|[^A-Za-z])(Zaishen Elite)(?=[^A-Za-z]|$)/gi, '$1战承精英');
data=data.replace(/(^|[^A-Za-z])(Maatu Keep)(?=[^A-Za-z]|$)/gi, '$1麻都堡垒');
data=data.replace(/(^|[^A-Za-z])(Zin Ku Corridor)(?=[^A-Za-z]|$)/gi, '$1辛库走廊');
data=data.replace(/(^|[^A-Za-z])(Brauer Academy)(?=[^A-Za-z]|$)/gi, '$1巴而学院');
data=data.replace(/(^|[^A-Za-z])(Durheim Archives)(?=[^A-Za-z]|$)/gi, '$1杜汉姆卷藏室');
data=data.replace(/(^|[^A-Za-z])(Bai Paasu Reach)(?=[^A-Za-z]|$)/gi, '$1拜巴蘇区域');
data=data.replace(/(^|[^A-Za-z])(Seafarer's Rest)(?=[^A-Za-z]|$)/gi, '$1航海者休息处');
data=data.replace(/(^|[^A-Za-z])(Vizunah Square Local Quarter)(?=[^A-Za-z]|$)/gi, '$1薇茹广场 本地');
data=data.replace(/(^|[^A-Za-z])(Vizunah Square Foreign Quarter)(?=[^A-Za-z]|$)/gi, '$1薇茹广场 外地');
data=data.replace(/(^|[^A-Za-z])(Fort Aspenwood - Luxon)(?=[^A-Za-z]|$)/gi, '$1红 - 杨木要塞 - 红');
data=data.replace(/(^|[^A-Za-z])(Fort Aspenwood - Kurzick)(?=[^A-Za-z]|$)/gi, '$1蓝 - 杨木要塞 - 蓝');
data=data.replace(/(^|[^A-Za-z])(The Jade Quarry - Luxon)(?=[^A-Za-z]|$)/gi, '$1红 - 翡翠矿场 - 红');
data=data.replace(/(^|[^A-Za-z])(The Jade Quarry - Kurzick)(?=[^A-Za-z]|$)/gi, '$1蓝 - 翡翠矿场 - 蓝');
data=data.replace(/(^|[^A-Za-z])(The Marketplace)(?=[^A-Za-z]|$)/gi, '$1市集');
data=data.replace(/(^|[^A-Za-z])(The Deep)(?=[^A-Za-z]|$)/gi, '$1深渊');
data=data.replace(/(^|[^A-Za-z])(Saltspray Beach - Luxon)(?=[^A-Za-z]|$)/gi, '$1红 - 盐滩 - 红');
data=data.replace(/(^|[^A-Za-z])(Saltspray Beach - Kurzick)(?=[^A-Za-z]|$)/gi, '$1蓝 - 盐滩 - 蓝');
data=data.replace(/(^|[^A-Za-z])(Heroes Ascent)(?=[^A-Za-z]|$)/gi, '$1Heroes Ascent');
data=data.replace(/(^|[^A-Za-z])(Grenz Frontier - Luxon)(?=[^A-Za-z]|$)/gi, '$1红 - 葛伦斯领域 - 红');
data=data.replace(/(^|[^A-Za-z])(Grenz Frontier - Kurzick)(?=[^A-Za-z]|$)/gi, '$1蓝 - 葛伦斯领域 - 蓝');
data=data.replace(/(^|[^A-Za-z])(The Ancestral Lands - Luxon)(?=[^A-Za-z]|$)/gi, '$1红 - 先人圣地 - 红');
data=data.replace(/(^|[^A-Za-z])(The Ancestral Lands - Kurzick)(?=[^A-Za-z]|$)/gi, '$1蓝 - 先人圣地 - 蓝');
data=data.replace(/(^|[^A-Za-z])(Etnaran Keys - Luxon)(?=[^A-Za-z]|$)/gi, '$1红 - Etnaran Keys - 红');
data=data.replace(/(^|[^A-Za-z])(Etnaran Keys - Kurzick)(?=[^A-Za-z]|$)/gi, '$1蓝 - Etnaran Keys - 蓝');
data=data.replace(/(^|[^A-Za-z])(Kaanai Canyon - Luxon)(?=[^A-Za-z]|$)/gi, '$1红 - Kaanai Canyon - 红');
data=data.replace(/(^|[^A-Za-z])(Kaanai Canyon - Kurzick)(?=[^A-Za-z]|$)/gi, '$1蓝 - Kaanai Canyon - 蓝');
data=data.replace(/(^|[^A-Za-z])(Tanglewood Copse)(?=[^A-Za-z]|$)/gi, '$1谭格塢树林');
data=data.replace(/(^|[^A-Za-z])(Saint Anjeka's Shrine)(?=[^A-Za-z]|$)/gi, '$1圣者安捷卡的祭坛');
data=data.replace(/(^|[^A-Za-z])(Eredon Terrace)(?=[^A-Za-z]|$)/gi, '$1而雷登平地');
data=data.replace(/(^|[^A-Za-z])(Dragon Arena)(?=[^A-Za-z]|$)/gi, '$1竞技场/龙');
data=data.replace(/(^|[^A-Za-z])(Camp Hojanu)(?=[^A-Za-z]|$)/gi, '$1何加努营地');
data=data.replace(/(^|[^A-Za-z])(Wehhan Terraces)(?=[^A-Za-z]|$)/gi, '$1薇恩平台');
data=data.replace(/(^|[^A-Za-z])(Yohlon Haven)(?=[^A-Za-z]|$)/gi, '$1犹朗避难所');
data=data.replace(/(^|[^A-Za-z])(Sunspear Sanctuary)(?=[^A-Za-z]|$)/gi, '$1日戟避难所');
data=data.replace(/(^|[^A-Za-z])(Aspenwood Gate - Kurzick)(?=[^A-Za-z]|$)/gi, '$1蓝 - 杨木大门 - 蓝');
data=data.replace(/(^|[^A-Za-z])(Aspenwood Gate - Luxon)(?=[^A-Za-z]|$)/gi, '$1红 - 杨木大门 - 红');
data=data.replace(/(^|[^A-Za-z])(Jade Flats Kurzick)(?=[^A-Za-z]|$)/gi, '$1蓝 - 翡翠浅滩 - 蓝');
data=data.replace(/(^|[^A-Za-z])(Jade Flats Luxon)(?=[^A-Za-z]|$)/gi, '$1红 - 翡翠浅滩 - 红');
data=data.replace(/(^|[^A-Za-z])(Chantry of Secrets)(?=[^A-Za-z]|$)/gi, '$1隐密教堂');
data=data.replace(/(^|[^A-Za-z])(Mihanu Township)(?=[^A-Za-z]|$)/gi, '$1米哈努小镇');
data=data.replace(/(^|[^A-Za-z])(Basalt Grotto)(?=[^A-Za-z]|$)/gi, '$1玄武岩石穴');
data=data.replace(/(^|[^A-Za-z])(Honur Hill)(?=[^A-Za-z]|$)/gi, '$1霍奴而丘陵');
data=data.replace(/(^|[^A-Za-z])(Yahnur Market)(?=[^A-Za-z]|$)/gi, '$1雅诺而市集');
data=data.replace(/(^|[^A-Za-z])(The Kodash Bazaar)(?=[^A-Za-z]|$)/gi, '$1库丹西市集广场');
data=data.replace(/(^|[^A-Za-z])(Venta Cemetery)(?=[^A-Za-z]|$)/gi, '$1凡特墓地');
data=data.replace(/(^|[^A-Za-z])(Kodonur Crossroads)(?=[^A-Za-z]|$)/gi, '$1科登诺路口');
data=data.replace(/(^|[^A-Za-z])(Rilohn Refuge)(?=[^A-Za-z]|$)/gi, '$1里欧恩难民营');
data=data.replace(/(^|[^A-Za-z])(Pogahn Passage)(?=[^A-Za-z]|$)/gi, '$1波甘驿站');
data=data.replace(/(^|[^A-Za-z])(Moddok Crevice)(?=[^A-Za-z]|$)/gi, '$1摩多克裂缝');
data=data.replace(/(^|[^A-Za-z])(Tihark Orchard)(?=[^A-Za-z]|$)/gi, '$1提亚克林地');
data=data.replace(/(^|[^A-Za-z])(Sunspear Great Hall)(?=[^A-Za-z]|$)/gi, '$1日戟大会堂');
data=data.replace(/(^|[^A-Za-z])(Dzagonur Bastion)(?=[^A-Za-z]|$)/gi, '$1蕯岗诺堡');
data=data.replace(/(^|[^A-Za-z])(Dasha Vestibule)(?=[^A-Za-z]|$)/gi, '$1达沙走廊');
data=data.replace(/(^|[^A-Za-z])(Grand Court of Sebelkeh)(?=[^A-Za-z]|$)/gi, '$1希贝克大宫廷');
data=data.replace(/(^|[^A-Za-z])(Bone Palace)(?=[^A-Za-z]|$)/gi, '$1白骨宫殿');
data=data.replace(/(^|[^A-Za-z])(The Mouth of Torment)(?=[^A-Za-z]|$)/gi, '$1苦痛之地隘口');
data=data.replace(/(^|[^A-Za-z])(Lair of the Forgotten)(?=[^A-Za-z]|$)/gi, '$1被遗忘者的巢穴');
data=data.replace(/(^|[^A-Za-z])(Kamadan)(?=[^A-Za-z]|$)/gi, '$1卡玛丹');
data=data.replace(/(^|[^A-Za-z])(Gate of Torment)(?=[^A-Za-z]|$)/gi, '$1苦痛之门');
data=data.replace(/(^|[^A-Za-z])(Beknur Harbor)(?=[^A-Za-z]|$)/gi, '$1别克诺港');
data=data.replace(/(^|[^A-Za-z])(Rollerbeetle Racing)(?=[^A-Za-z]|$)/gi, '$1Rollerbeetle Racing');
data=data.replace(/(^|[^A-Za-z])(Gate of Fear)(?=[^A-Za-z]|$)/gi, '$1恐惧之门');
data=data.replace(/(^|[^A-Za-z])(Gate of Secrets)(?=[^A-Za-z]|$)/gi, '$1奥秘之门');
data=data.replace(/(^|[^A-Za-z])(Gate of Anguish)(?=[^A-Za-z]|$)/gi, '$1悲难之门');
data=data.replace(/(^|[^A-Za-z])(Jennurs Horde)(?=[^A-Za-z]|$)/gi, '$1征纳群落');
data=data.replace(/(^|[^A-Za-z])(Nundu Bay)(?=[^A-Za-z]|$)/gi, '$1纳度湾');
data=data.replace(/(^|[^A-Za-z])(Gate of Desolation)(?=[^A-Za-z]|$)/gi, '$1荒芜之地入口');
data=data.replace(/(^|[^A-Za-z])(Champions Dawn)(?=[^A-Za-z]|$)/gi, '$1勇士曙光');
data=data.replace(/(^|[^A-Za-z])(Ruins of Morah)(?=[^A-Za-z]|$)/gi, '$1莫拉废墟');
data=data.replace(/(^|[^A-Za-z])(Kodlonu Hamlet)(?=[^A-Za-z]|$)/gi, '$1克拓怒-哈姆雷特');
data=data.replace(/(^|[^A-Za-z])(Jokanur Diggings)(?=[^A-Za-z]|$)/gi, '$1卓坎诺挖掘点');
data=data.replace(/(^|[^A-Za-z])(Blacktide Den)(?=[^A-Za-z]|$)/gi, '$1黑潮之穴');
data=data.replace(/(^|[^A-Za-z])(Consulate Docks)(?=[^A-Za-z]|$)/gi, '$1领事馆码头');
data=data.replace(/(^|[^A-Za-z])(Gate of Pain)(?=[^A-Za-z]|$)/gi, '$1惩罚之门');
data=data.replace(/(^|[^A-Za-z])(Gate of Madness)(?=[^A-Za-z]|$)/gi, '$1疯狂之门');
data=data.replace(/(^|[^A-Za-z])(Abaddons Gate)(?=[^A-Za-z]|$)/gi, '$1亚霸顿之门');
data=data.replace(/(^|[^A-Za-z])(Sunspear Arena)(?=[^A-Za-z]|$)/gi, '$1竞技场/日戟');
data=data.replace(/(^|[^A-Za-z])(The Astralarium)(?=[^A-Za-z]|$)/gi, '$1亚斯特拉利姆');
data=data.replace(/(^|[^A-Za-z])(Chahbek Village)(?=[^A-Za-z]|$)/gi, '$1夏贝克村庄');
data=data.replace(/(^|[^A-Za-z])(Remains of Sahlahja)(?=[^A-Za-z]|$)/gi, '$1萨拉加遗址');
data=data.replace(/(^|[^A-Za-z])(Hero Battles)(?=[^A-Za-z]|$)/gi, '$1Hero Battles');
data=data.replace(/(^|[^A-Za-z])(Dajkah Inlet)(?=[^A-Za-z]|$)/gi, '$1达卡港');
data=data.replace(/(^|[^A-Za-z])(The Shadow Nexus)(?=[^A-Za-z]|$)/gi, '$1The Shadow Nexus');
data=data.replace(/(^|[^A-Za-z])(Gate of the Nightfallen Lands)(?=[^A-Za-z]|$)/gi, '$1Gate of the Nightfallen Lands');
data=data.replace(/(^|[^A-Za-z])(Vlox's Falls)(?=[^A-Za-z]|$)/gi, '$1瀑布');
data=data.replace(/(^|[^A-Za-z])(Gadd's Encampment)(?=[^A-Za-z]|$)/gi, '$1盖得');
data=data.replace(/(^|[^A-Za-z])(Umbral Grotto)(?=[^A-Za-z]|$)/gi, '$1阴影石穴');
data=data.replace(/(^|[^A-Za-z])(Rata Sum)(?=[^A-Za-z]|$)/gi, '$1顶点');
data=data.replace(/(^|[^A-Za-z])(Tarnished Haven)(?=[^A-Za-z]|$)/gi, '$1灰暗避难所');
data=data.replace(/(^|[^A-Za-z])(Eye of the North)(?=[^A-Za-z]|$)/gi, '$1极地之眼');
data=data.replace(/(^|[^A-Za-z])(Sifhalla)(?=[^A-Za-z]|$)/gi, '$1袭哈拉');
data=data.replace(/(^|[^A-Za-z])(Gunnar's Hold)(?=[^A-Za-z]|$)/gi, '$1甘拿');
data=data.replace(/(^|[^A-Za-z])(Olafstead)(?=[^A-Za-z]|$)/gi, '$1欧拉夫之地');
data=data.replace(/(^|[^A-Za-z])(Doomlore Shrine)(?=[^A-Za-z]|$)/gi, '$1末日传说神殿');
data=data.replace(/(^|[^A-Za-z])(Longeye's Ledge)(?=[^A-Za-z]|$)/gi, '$1长眼');
data=data.replace(/(^|[^A-Za-z])(Central Transfer Chamber)(?=[^A-Za-z]|$)/gi, '$1中央转送室');
data=data.replace(/(^|[^A-Za-z])(Boreal Station)(?=[^A-Za-z]|$)/gi, '$1北极驻地');
data=data.replace(/(^|[^A-Za-z])(Costume Brawl)(?=[^A-Za-z]|$)/gi, '$1Costume Brawl');
data=data.replace(/(^|[^A-Za-z])(Zaishen Menagerie)(?=[^A-Za-z]|$)/gi, '$1战承动物园');
data=data.replace(/(^|[^A-Za-z])(Codex Arena)(?=[^A-Za-z]|$)/gi, '$1竞技场/Codex');
data=data.replace(/(^|[^A-Za-z])(Lions Arch - Halloween)(?=[^A-Za-z]|$)/gi, '$1狮城 - 万圣节');
data=data.replace(/(^|[^A-Za-z])(Lions Arch - Wintersday)(?=[^A-Za-z]|$)/gi, '$1狮城 - 冬日');
data=data.replace(/(^|[^A-Za-z])(Lions Arch - Canthan New Year)(?=[^A-Za-z]|$)/gi, '$1狮城 - 二章新年');
data=data.replace(/(^|[^A-Za-z])(Ascalon City - Wintersday)(?=[^A-Za-z]|$)/gi, '$1阿城 - 冬日');
data=data.replace(/(^|[^A-Za-z])(Droknars Forge - Halloween)(?=[^A-Za-z]|$)/gi, '$1熔炉 - 万圣节');
data=data.replace(/(^|[^A-Za-z])(Droknars Forge - Wintersday)(?=[^A-Za-z]|$)/gi, '$1熔炉 - 冬日');
data=data.replace(/(^|[^A-Za-z])(Tomb of the Primeval Kings - Halloween)(?=[^A-Za-z]|$)/gi, '$1先王之墓 - 万圣节');
data=data.replace(/(^|[^A-Za-z])(Shing Jea - Dragon Festival)(?=[^A-Za-z]|$)/gi, '$1星岬寺 - 龙节');
data=data.replace(/(^|[^A-Za-z])(Shing Jea - Canthan New Year)(?=[^A-Za-z]|$)/gi, '$1星岬寺 - 二章新年');
data=data.replace(/(^|[^A-Za-z])(Eye of the North - Wintersday)(?=[^A-Za-z]|$)/gi, '$1极地之眼 - 冬日');
data=data.replace(/(^|[^A-Za-z])(Embark Beach)(?=[^A-Za-z]|$)/gi, '$1登陆滩');
