data=data.replace(/(^|[^A-Za-z])(Ice Tooth Cave)(?=[^A-Za-z]|$)/gi, '$1冰牙洞穴');
data=data.replace(/(^|[^A-Za-z])(Anvil Rock)(?=[^A-Za-z]|$)/gi, '$1铁砧石');
data=data.replace(/(^|[^A-Za-z])(Frostfire Dryder)(?=[^A-Za-z]|$)/gi, '$1霜火蛛化精灵');
data=data.replace(/(^|[^A-Za-z])(Frostfire Fang)(?=[^A-Za-z]|$)/gi, '$1霜火尖牙');
data=data.replace(/(^|[^A-Za-z])(Boreas Seabed)(?=[^A-Za-z]|$)/gi, '$1风神海床');
data=data.replace(/(^|[^A-Za-z])(Pongmei Valley)(?=[^A-Za-z]|$)/gi, '$1朋美谷');
data=data.replace(/(^|[^A-Za-z])(Rot Wallow)(?=[^A-Za-z]|$)/gi, '$1腐败兽');
data=data.replace(/(^|[^A-Za-z])(Rot Wallow Tusk)(?=[^A-Za-z]|$)/gi, '$1腐败兽獠牙');
data=data.replace(/(^|[^A-Za-z])(Elona Reach)(?=[^A-Za-z]|$)/gi, '$1伊洛那流域');
data=data.replace(/(^|[^A-Za-z])(Diviner's Ascent)(?=[^A-Za-z]|$)/gi, '$1预言者之坡');
data=data.replace(/(^|[^A-Za-z])(Sand Drake)(?=[^A-Za-z]|$)/gi, '$1沙龙兽');
data=data.replace(/(^|[^A-Za-z])(Topaz Crest)(?=[^A-Za-z]|$)/gi, '$1黄宝石颈脊');
data=data.replace(/(^|[^A-Za-z])(Rata Sum)(?=[^A-Za-z]|$)/gi, '$1洛达顶点');
data=data.replace(/(^|[^A-Za-z])(Magus Stones)(?=[^A-Za-z]|$)/gi, '$1玛古斯之石');
data=data.replace(/(^|[^A-Za-z])(Lifeweaver)(?=[^A-Za-z]|$)/gi, '$1织命者');
data=data.replace(/(^|[^A-Za-z])(Bloodweaver)(?=[^A-Za-z]|$)/gi, '$1织血者');
data=data.replace(/(^|[^A-Za-z])(Venomweaver)(?=[^A-Za-z]|$)/gi, '$1织恨者');
data=data.replace(/(^|[^A-Za-z])(Spider)(?=[^A-Za-z]|$)/gi, '$1蜘蛛');
data=data.replace(/(^|[^A-Za-z])(Weaver Leg)(?=[^A-Za-z]|$)/gi, '$1编织者的腿');
data=data.replace(/(^|[^A-Za-z])(Yahnur Market)(?=[^A-Za-z]|$)/gi, '$1雅诺尔市集');
data=data.replace(/(^|[^A-Za-z])(Vehtendi Valley)(?=[^A-Za-z]|$)/gi, '$1巍天帝峡谷');
data=data.replace(/(^|[^A-Za-z])(Storm Jacaranda)(?=[^A-Za-z]|$)/gi, '$1暴风荆棘');
data=data.replace(/(^|[^A-Za-z])(Mirage Iboga)(?=[^A-Za-z]|$)/gi, '$1幻象伊波枷');
data=data.replace(/(^|[^A-Za-z])(Enchanted Brambles)(?=[^A-Za-z]|$)/gi, '$1魔法树根');
data=data.replace(/(^|[^A-Za-z])(Whistling Thornbrush)(?=[^A-Za-z]|$)/gi, '$1荆棘之藤');
data=data.replace(/(^|[^A-Za-z])(Sentient Spore)(?=[^A-Za-z]|$)/gi, '$1知觉孢子');
data=data.replace(/(^|[^A-Za-z])(Ahoj)(?=[^A-Za-z]|$)/gi, '$1亚禾');
data=data.replace(/(^|[^A-Za-z])(Bottle of Vabbian Wine)(?=[^A-Za-z]|$)/gi, '$1瓦贝红酒');
data=data.replace(/(^|[^A-Za-z])(Jarimiya the Unmerciful)(?=[^A-Za-z]|$)/gi, '$1残酷 贾米里');
data=data.replace(/(^|[^A-Za-z])(Blacktide Den)(?=[^A-Za-z]|$)/gi, '$1黑潮之穴');
data=data.replace(/(^|[^A-Za-z])(Lahtenda Bog)(?=[^A-Za-z]|$)/gi, '$1洛天帝沼泽');
data=data.replace(/(^|[^A-Za-z])(Mandragor Imp)(?=[^A-Za-z]|$)/gi, '$1曼陀罗恶魔');
data=data.replace(/(^|[^A-Za-z])(Mandragor Slither)(?=[^A-Za-z]|$)/gi, '$1曼陀罗之藤');
data=data.replace(/(^|[^A-Za-z])(Stoneflesh Mandragor)(?=[^A-Za-z]|$)/gi, '$1曼陀罗石根');
data=data.replace(/(^|[^A-Za-z])(Mandragor Swamproot)(?=[^A-Za-z]|$)/gi, '$1曼陀罗根');
data=data.replace(/(^|[^A-Za-z])(Vasburg Armory)(?=[^A-Za-z]|$)/gi, '$1维思柏兵营');
data=data.replace(/(^|[^A-Za-z])(The Eternal Grove)(?=[^A-Za-z]|$)/gi, '$1永恒之林探索区');
data=data.replace(/(^|[^A-Za-z])(Skill Hungry Gaki)(?=[^A-Za-z]|$)/gi, '$1灵巧的饿鬼');
data=data.replace(/(^|[^A-Za-z])(Pain Hungry Gaki)(?=[^A-Za-z]|$)/gi, '$1痛苦的饿鬼');
data=data.replace(/(^|[^A-Za-z])(The Time Eater)(?=[^A-Za-z]|$)/gi, '$1时间吞噬者');
data=data.replace(/(^|[^A-Za-z])(The Scar Eater)(?=[^A-Za-z]|$)/gi, '$1疤痕吞噬者');
data=data.replace(/(^|[^A-Za-z])(Quarrel Falls)(?=[^A-Za-z]|$)/gi, '$1怨言瀑布');
data=data.replace(/(^|[^A-Za-z])(Silverwood)(?=[^A-Za-z]|$)/gi, '$1银树');
data=data.replace(/(^|[^A-Za-z])(Maguuma Warrior)(?=[^A-Za-z]|$)/gi, '$1梅古玛战士');
data=data.replace(/(^|[^A-Za-z])(Maguuma Hunter)(?=[^A-Za-z]|$)/gi, '$1梅古玛猎人');
data=data.replace(/(^|[^A-Za-z])(Maguuma Protector)(?=[^A-Za-z]|$)/gi, '$1梅古玛守护者');
data=data.replace(/(^|[^A-Za-z])(Maguuma Mane)(?=[^A-Za-z]|$)/gi, '$1梅古玛鬃毛');
data=data.replace(/(^|[^A-Za-z])(Seeker's Passage)(?=[^A-Za-z]|$)/gi, '$1探索者通道');
data=data.replace(/(^|[^A-Za-z])(Salt Flats)(?=[^A-Za-z]|$)/gi, '$1盐滩');
data=data.replace(/(^|[^A-Za-z])(The Amnoon Oasis)(?=[^A-Za-z]|$)/gi, '$1安奴绿洲');
data=data.replace(/(^|[^A-Za-z])(Prophet's Path)(?=[^A-Za-z]|$)/gi, '$1先知之路');
data=data.replace(/(^|[^A-Za-z])(Jade Scarab)(?=[^A-Za-z]|$)/gi, '$1翡翠圣甲虫');
data=data.replace(/(^|[^A-Za-z])(Jade Mandible)(?=[^A-Za-z]|$)/gi, '$1翡翠下颚骨');
data=data.replace(/(^|[^A-Za-z])(Temple of the Ages)(?=[^A-Za-z]|$)/gi, '$1辛库走廊');
data=data.replace(/(^|[^A-Za-z])(Sunjiang District)(?=[^A-Za-z]|$)/gi, '$1孙江行政区');
data=data.replace(/(^|[^A-Za-z])(Sunjiang District)(?=[^A-Za-z]|$)/gi, '$1孙江行政区主线');
data=data.replace(/(^|[^A-Za-z])(Shenzun Tunnels)(?=[^A-Za-z]|$)/gi, '$1申赞通道');
data=data.replace(/(^|[^A-Za-z])(Afflicted)(?=[^A-Za-z]|$)/gi, '$1被感染的');
data=data.replace(/(^|[^A-Za-z])(Putrid Cyst)(?=[^A-Za-z]|$)/gi, '$1腐败胞囊');
data=data.replace(/(^|[^A-Za-z])(Temple of the Ages)(?=[^A-Za-z]|$)/gi, '$1世纪神殿');
data=data.replace(/(^|[^A-Za-z])(The Black Curtain)(?=[^A-Za-z]|$)/gi, '$1黑色帷幕');
data=data.replace(/(^|[^A-Za-z])(Kessex Peak)(?=[^A-Za-z]|$)/gi, '$1凯席斯山峰');
data=data.replace(/(^|[^A-Za-z])(Talmark Wilderness)(?=[^A-Za-z]|$)/gi, '$1突马克荒地');
data=data.replace(/(^|[^A-Za-z])(Forest Minotaur)(?=[^A-Za-z]|$)/gi, '$1森林牛头怪');
data=data.replace(/(^|[^A-Za-z])(Forest Minotaur Horn)(?=[^A-Za-z]|$)/gi, '$1森林牛头怪的角');
data=data.replace(/(^|[^A-Za-z])(The Astralarium)(?=[^A-Za-z]|$)/gi, '$1亚斯特拉利姆');
data=data.replace(/(^|[^A-Za-z])(Zehlon Reach)(?=[^A-Za-z]|$)/gi, '$1列隆流域');
data=data.replace(/(^|[^A-Za-z])(Beknur Harbor)(?=[^A-Za-z]|$)/gi, '$1别克诺港');
data=data.replace(/(^|[^A-Za-z])(Issnur Isles)(?=[^A-Za-z]|$)/gi, '$1伊斯诺岛');
data=data.replace(/(^|[^A-Za-z])(Skale Blighter)(?=[^A-Za-z]|$)/gi, '$1黑暗鳞怪');
data=data.replace(/(^|[^A-Za-z])(Frigid Skale)(?=[^A-Za-z]|$)/gi, '$1寒冰鳞怪');
data=data.replace(/(^|[^A-Za-z])(Ridgeback Skale)(?=[^A-Za-z]|$)/gi, '$1脊背鳞怪');
data=data.replace(/(^|[^A-Za-z])(Skale Fin)(?=[^A-Za-z]|$)/gi, '$1鳞怪鳍');
data=data.replace(/(^|[^A-Za-z])(Chef Panjoh)(?=[^A-Za-z]|$)/gi, '$1大厨 潘乔');
data=data.replace(/(^|[^A-Za-z])(Bowl of Skalefin Soup)(?=[^A-Za-z]|$)/gi, '$1鳞怪鳍汤');
data=data.replace(/(^|[^A-Za-z])(Sage Lands)(?=[^A-Za-z]|$)/gi, '$1荒原');
data=data.replace(/(^|[^A-Za-z])(Mamnoon Lagoon)(?=[^A-Za-z]|$)/gi, '$1玛奴泻湖');
data=data.replace(/(^|[^A-Za-z])(Henge of Denravi)(?=[^A-Za-z]|$)/gi, '$1丹拉维圣地');
data=data.replace(/(^|[^A-Za-z])(Tangle Root)(?=[^A-Za-z]|$)/gi, '$1纠结之根');
data=data.replace(/(^|[^A-Za-z])(Dry Top)(?=[^A-Za-z]|$)/gi, '$1干燥高地');
data=data.replace(/(^|[^A-Za-z])(Root Behe​​moth)(?=[^A-Za-z]|$)/gi, '$1根巨兽');
data=data.replace(/(^|[^A-Za-z])(Behemoth Jaw)(?=[^A-Za-z]|$)/gi, '$1巨兽颚');
data=data.replace(/(^|[^A-Za-z])(Sifhalla)(?=[^A-Za-z]|$)/gi, '$1袭哈拉');
data=data.replace(/(^|[^A-Za-z])(Jaga Moraine)(?=[^A-Za-z]|$)/gi, '$1亚加摩瑞恩');
data=data.replace(/(^|[^A-Za-z])(Berserking Bison)(?=[^A-Za-z]|$)/gi, '$1海冶克狂战士');
data=data.replace(/(^|[^A-Za-z])(Berserking Minotaur)(?=[^A-Za-z]|$)/gi, '$1牛头怪狂战士');
data=data.replace(/(^|[^A-Za-z])(Berserking Wendigo)(?=[^A-Za-z]|$)/gi, '$1狂战士 纹帝哥');
data=data.replace(/(^|[^A-Za-z])(Berserking Aurochs)(?=[^A-Za-z]|$)/gi, '$1棘狼狂战士');
data=data.replace(/(^|[^A-Za-z])(Berserker Horn)(?=[^A-Za-z]|$)/gi, '$1狂战士的角');
data=data.replace(/(^|[^A-Za-z])(Brauer Academy)(?=[^A-Za-z]|$)/gi, '$1巴尔学院');
data=data.replace(/(^|[^A-Za-z])(Drazach Thicket)(?=[^A-Za-z]|$)/gi, '$1德瑞扎灌木林');
data=data.replace(/(^|[^A-Za-z])(Tanglewood Copse)(?=[^A-Za-z]|$)/gi, '$1谭格坞树林');
data=data.replace(/(^|[^A-Za-z])(Pongmei Valley)(?=[^A-Za-z]|$)/gi, '$1朋美谷');
data=data.replace(/(^|[^A-Za-z])(Undergrowth)(?=[^A-Za-z]|$)/gi, '$1矮树丛');
data=data.replace(/(^|[^A-Za-z])(Dragon Moss)(?=[^A-Za-z]|$)/gi, '$1龙苔');
data=data.replace(/(^|[^A-Za-z])(Dragon Root)(?=[^A-Za-z]|$)/gi, '$1龙根');
data=data.replace(/(^|[^A-Za-z])(Fishermen's Haven)(?=[^A-Za-z]|$)/gi, '$1渔人避风港');
data=data.replace(/(^|[^A-Za-z])(Stingray Strand)(?=[^A-Za-z]|$)/gi, '$1魟鱼湖滨');
data=data.replace(/(^|[^A-Za-z])(Tears of the Fallen)(?=[^A-Za-z]|$)/gi, '$1战死者之泪');
data=data.replace(/(^|[^A-Za-z])(Grand Drake)(?=[^A-Za-z]|$)/gi, '$1强龙兽');
data=data.replace(/(^|[^A-Za-z])(Sanctum Cay)(?=[^A-Za-z]|$)/gi, '$1神圣沙滩主线');
data=data.replace(/(^|[^A-Za-z])(Lightning Drake)(?=[^A-Za-z]|$)/gi, '$1闪光龙兽');
data=data.replace(/(^|[^A-Za-z])(Spiked Crest)(?=[^A-Za-z]|$)/gi, '$1尖刺的颈脊');
data=data.replace(/(^|[^A-Za-z])(Imperial Sanctum)(?=[^A-Za-z]|$)/gi, '$1帝国圣所');
data=data.replace(/(^|[^A-Za-z])(Raisu Palace)(?=[^A-Za-z]|$)/gi, '$1莱苏皇宫');
data=data.replace(/(^|[^A-Za-z])(Shiro'k​​en)(?=[^A-Za-z]|$)/gi, '$1白影军团');
data=data.replace(/(^|[^A-Za-z])(Soul Stone)(?=[^A-Za-z]|$)/gi, '$1灵魂石');
data=data.replace(/(^|[^A-Za-z])(Tihark Orchard)(?=[^A-Za-z]|$)/gi, '$1提亚克林地');
data=data.replace(/(^|[^A-Za-z])(Forum Highlands)(?=[^A-Za-z]|$)/gi, '$1高地广场');
data=data.replace(/(^|[^A-Za-z])(Skree)(?=[^A-Za-z]|$)/gi, '$1鸟妖');
data=data.replace(/(^|[^A-Za-z])(Skree Wing)(?=[^A-Za-z]|$)/gi, '$1鸟妖翅膀');
data=data.replace(/(^|[^A-Za-z])(Serenity Temple)(?=[^A-Za-z]|$)/gi, '$1宁静神殿');
data=data.replace(/(^|[^A-Za-z])(Pockmark Flats)(?=[^A-Za-z]|$)/gi, '$1麻点平原');
data=data.replace(/(^|[^A-Za-z])(Storm Rider)(?=[^A-Za-z]|$)/gi, '$1暴风驾驭者');
data=data.replace(/(^|[^A-Za-z])(Stormy Eye)(?=[^A-Za-z]|$)/gi, '$1暴风之眼');
data=data.replace(/(^|[^A-Za-z])(Gates of Kryta)(?=[^A-Za-z]|$)/gi, '$1科瑞塔之门');
data=data.replace(/(^|[^A-Za-z])(Scoundrel's Rise)(?=[^A-Za-z]|$)/gi, '$1恶汉山丘');
data=data.replace(/(^|[^A-Za-z])(Griffon's Mouth)(?=[^A-Za-z]|$)/gi, '$1狮鹭兽隘口');
data=data.replace(/(^|[^A-Za-z])(Spiritwood Plank)(?=[^A-Za-z]|$)/gi, '$1心灵之板');
data=data.replace(/(^|[^A-Za-z])(Tsumei Village)(?=[^A-Za-z]|$)/gi, '$1苏梅村');
data=data.replace(/(^|[^A-Za-z])(Panjiang Peninsula)(?=[^A-Za-z]|$)/gi, '$1班让半岛');
data=data.replace(/(^|[^A-Za-z])(Naga)(?=[^A-Za-z]|$)/gi, '$1纳迦');
data=data.replace(/(^|[^A-Za-z])(Naga Hide)(?=[^A-Za-z]|$)/gi, '$1纳迦皮');
data=data.replace(/(^|[^A-Za-z])(Sifhalla)(?=[^A-Za-z]|$)/gi, '$1袭哈拉');
data=data.replace(/(^|[^A-Za-z])(Drakkar Lake)(?=[^A-Za-z]|$)/gi, '$1卓卡湖');
data=data.replace(/(^|[^A-Za-z])(Frozen Elemental)(?=[^A-Za-z]|$)/gi, '$1冰元素');
data=data.replace(/(^|[^A-Za-z])(Pile of Elemental Dust)(?=[^A-Za-z]|$)/gi, '$1元素之土');
data=data.replace(/(^|[^A-Za-z])(Leviathan Pits)(?=[^A-Za-z]|$)/gi, '$1卑尔根温泉');
data=data.replace(/(^|[^A-Za-z])(Silent Surf)(?=[^A-Za-z]|$)/gi, '$1尼伯山丘');
data=data.replace(/(^|[^A-Za-z])(Oni)(?=[^A-Za-z]|$)/gi, '$1柯瑞塔北部');
data=data.replace(/(^|[^A-Za-z])(Keen Oni Talon)(?=[^A-Za-z]|$)/gi, '$1硬瘤');
data=data.replace(/(^|[^A-Za-z])(Leviathan Pits)(?=[^A-Za-z]|$)/gi, '$1利拜亚森矿场');
data=data.replace(/(^|[^A-Za-z])(Silent Surf)(?=[^A-Za-z]|$)/gi, '$1寂静之浪');
data=data.replace(/(^|[^A-Za-z])(Seafarer's Rest)(?=[^A-Za-z]|$)/gi, '$1航海者休憩处');
data=data.replace(/(^|[^A-Za-z])(Oni)(?=[^A-Za-z]|$)/gi, '$1鬼');
data=data.replace(/(^|[^A-Za-z])(Keen Oni Talon)(?=[^A-Za-z]|$)/gi, '$1鬼爪');
data=data.replace(/(^|[^A-Za-z])(Ice Caves of Sorrow)(?=[^A-Za-z]|$)/gi, '$1悲伤冰谷');
data=data.replace(/(^|[^A-Za-z])(Icedome)(?=[^A-Za-z]|$)/gi, '$1冰顶');
data=data.replace(/(^|[^A-Za-z])(Siege Ice Golem)(?=[^A-Za-z]|$)/gi, '$1攻城冰高仑');
data=data.replace(/(^|[^A-Za-z])(Icy Lodestone)(?=[^A-Za-z]|$)/gi, '$1冰磁石');
data=data.replace(/(^|[^A-Za-z])(Augury Rock)(?=[^A-Za-z]|$)/gi, '$1占卜之石');
data=data.replace(/(^|[^A-Za-z])(Skyward Reach)(?=[^A-Za-z]|$)/gi, '$1天际流域');
data=data.replace(/(^|[^A-Za-z])(Destiny's Gorge)(?=[^A-Za-z]|$)/gi, '$1命运峡谷');
data=data.replace(/(^|[^A-Za-z])(Prophet's Path)(?=[^A-Za-z]|$)/gi, '$1探索者通道');
data=data.replace(/(^|[^A-Za-z])(Salt Flats)(?=[^A-Za-z]|$)/gi, '$1盐滩');
data=data.replace(/(^|[^A-Za-z])(Storm Kin)(?=[^A-Za-z]|$)/gi, '$1风暴魔');
data=data.replace(/(^|[^A-Za-z])(Shriveled Eye)(?=[^A-Za-z]|$)/gi, '$1干枯的眼睛');
data=data.replace(/(^|[^A-Za-z])(Camp Hojanu)(?=[^A-Za-z]|$)/gi, '$1何加努营地');
data=data.replace(/(^|[^A-Za-z])(Barbarous Shore)(?=[^A-Za-z]|$)/gi, '$1野蛮河岸');
data=data.replace(/(^|[^A-Za-z])(Corsair)(?=[^A-Za-z]|$)/gi, '$1海盗');
data=data.replace(/(^|[^A-Za-z])(Gold Doubloon)(?=[^A-Za-z]|$)/gi, '$1金古币');
data=data.replace(/(^|[^A-Za-z])(Dragon's Throat)(?=[^A-Za-z]|$)/gi, '$1龙喉');
data=data.replace(/(^|[^A-Za-z])(Shadow's Passage)(?=[^A-Za-z]|$)/gi, '$1阴暗通道');
data=data.replace(/(^|[^A-Za-z])(rare material trader)(?=[^A-Za-z]|$)/gi, '$1稀有材料商');
data=data.replace(/(^|[^A-Za-z])(Luxon faction)(?=[^A-Za-z]|$)/gi, '$1勒克森荣誉值');
data=data.replace(/(^|[^A-Za-z])(Jadeite Shard)(?=[^A-Za-z]|$)/gi, '$1硬玉');
data=data.replace(/(^|[^A-Za-z])(Port Sledge)(?=[^A-Za-z]|$)/gi, '$1雪橇港');
data=data.replace(/(^|[^A-Za-z])(Witman's Folly)(?=[^A-Za-z]|$)/gi, '$1威特曼的怪异建筑');
data=data.replace(/(^|[^A-Za-z])(Grawl)(?=[^A-Za-z]|$)/gi, '$1穴居人');
data=data.replace(/(^|[^A-Za-z])(Grawl Crone)(?=[^A-Za-z]|$)/gi, '$1穴居人巫婆');
data=data.replace(/(^|[^A-Za-z])(Intricate Grawl Necklace)(?=[^A-Za-z]|$)/gi, '$1精细的穴居人项链');
data=data.replace(/(^|[^A-Za-z])(The Mouth of Torment)(?=[^A-Za-z]|$)/gi, '$1苦痛之地隘口');
data=data.replace(/(^|[^A-Za-z])(Crystal Overlook)(?=[^A-Za-z]|$)/gi, '$1水晶高地');
data=data.replace(/(^|[^A-Za-z])(Ruins of Morah)(?=[^A-Za-z]|$)/gi, '$1摩拉废墟');
data=data.replace(/(^|[^A-Za-z])(Mandragor Sand Devil)(?=[^A-Za-z]|$)/gi, '$1曼陀罗沙恶魔');
data=data.replace(/(^|[^A-Za-z])(Mandragor Terror)(?=[^A-Za-z]|$)/gi, '$1惊骇曼陀罗');
data=data.replace(/(^|[^A-Za-z])(Ravenous Mandragor)(?=[^A-Za-z]|$)/gi, '$1曼陀罗贪婪者');
data=data.replace(/(^|[^A-Za-z])(Luminous Stone)(?=[^A-Za-z]|$)/gi, '$1发亮的石头');
data=data.replace(/(^|[^A-Za-z])(Dzagonur Bastion)(?=[^A-Za-z]|$)/gi, '$1萨岗诺棱堡');
data=data.replace(/(^|[^A-Za-z])(Wilderness of Bahdza)(?=[^A-Za-z]|$)/gi, '$1巴萨荒野');
data=data.replace(/(^|[^A-Za-z])(Behemoth Gravebane)(?=[^A-Za-z]|$)/gi, '$1剧毒巨兽');
data=data.replace(/(^|[^A-Za-z])(Scytheclaw Behe​​moth)(?=[^A-Za-z]|$)/gi, '$1镰刀爪巨兽');
data=data.replace(/(^|[^A-Za-z])(Behemoth Hide)(?=[^A-Za-z]|$)/gi, '$1巨兽皮革');
data=data.replace(/(^|[^A-Za-z])(Rata Sum)(?=[^A-Za-z]|$)/gi, '$1洛达顶点');
data=data.replace(/(^|[^A-Za-z])(Riven Earth)(?=[^A-Za-z]|$)/gi, '$1撕裂大地');
data=data.replace(/(^|[^A-Za-z])(Raptor)(?=[^A-Za-z]|$)/gi, '$1毒瑞克斯');
data=data.replace(/(^|[^A-Za-z])(Angorodon)(?=[^A-Za-z]|$)/gi, '$1安哥罗顿');
data=data.replace(/(^|[^A-Za-z])(Saurian Bone)(?=[^A-Za-z]|$)/gi, '$1蜥蜴骨头');
data=data.replace(/(^|[^A-Za-z])(Sanctum Cay)(?=[^A-Za-z]|$)/gi, '$1神圣沙滩');
data=data.replace(/(^|[^A-Za-z])(Stingray Strand)(?=[^A-Za-z]|$)/gi, '$1魟鱼湖滨');
data=data.replace(/(^|[^A-Za-z])(Fishermen's Haven)(?=[^A-Za-z]|$)/gi, '$1渔人避风港');
data=data.replace(/(^|[^A-Za-z])(Talmark Wilderness)(?=[^A-Za-z]|$)/gi, '$1突马克荒地');
data=data.replace(/(^|[^A-Za-z])(Inferno Imp)(?=[^A-Za-z]|$)/gi, '$1地狱小恶魔');
data=data.replace(/(^|[^A-Za-z])(Glowing Heart)(?=[^A-Za-z]|$)/gi, '$1灼热的心脏');
data=data.replace(/(^|[^A-Za-z])(House zu Heltzer)(?=[^A-Za-z]|$)/gi, '$1凤核议院');
data=data.replace(/(^|[^A-Za-z])(Ferndale)(?=[^A-Za-z]|$)/gi, '$1厥谷');
data=data.replace(/(^|[^A-Za-z])(Rare crafting material)(?=[^A-Za-z]|$)/gi, '$1稀有材料');
data=data.replace(/(^|[^A-Za-z])(Amber Chunk)(?=[^A-Za-z]|$)/gi, '$1琥珀');
data=data.replace(/(^|[^A-Za-z])(Kurzick Bureaucrat)(?=[^A-Za-z]|$)/gi, '$1库兹柯理事');
data=data.replace(/(^|[^A-Za-z])(Kodlonu Hamlet)(?=[^A-Za-z]|$)/gi, '$1克拓奴‧哈姆雷特');
data=data.replace(/(^|[^A-Za-z])(Issnur Isles)(?=[^A-Za-z]|$)/gi, '$1伊斯诺岛');
data=data.replace(/(^|[^A-Za-z])(Irontooth Drake)(?=[^A-Za-z]|$)/gi, '$1钢牙龙兽');
data=data.replace(/(^|[^A-Za-z])(Rilohn Refuge)(?=[^A-Za-z]|$)/gi, '$1里欧恩难民营主线');
data=data.replace(/(^|[^A-Za-z])(Steelfang Drake)(?=[^A-Za-z]|$)/gi, '$1硬甲龙兽');
data=data.replace(/(^|[^A-Za-z])(Chunk of Drake Flesh)(?=[^A-Za-z]|$)/gi, '$1大块龙兽肉');
data=data.replace(/(^|[^A-Za-z])(Chef Lonbahn)(?=[^A-Za-z]|$)/gi, '$1大厨 萝韩');
data=data.replace(/(^|[^A-Za-z])(Drake Kabob)(?=[^A-Za-z]|$)/gi, '$1烤龙兽肉');
data=data.replace(/(^|[^A-Za-z])(Beacon's Perch)(?=[^A-Za-z]|$)/gi, '$1毕肯高地');
data=data.replace(/(^|[^A-Za-z])(Lornar's Pass)(?=[^A-Za-z]|$)/gi, '$1洛拿斯通道');
data=data.replace(/(^|[^A-Za-z])(Tomb of the Primeval Kings)(?=[^A-Za-z]|$)/gi, '$1先王之墓');
data=data.replace(/(^|[^A-Za-z])(Banished Dream Rider)(?=[^A-Za-z]|$)/gi, '$1被放逐的梦想骑士');
data=data.replace(/(^|[^A-Za-z])(Phantom Residue)(?=[^A-Za-z]|$)/gi, '$1幻影残留物');
data=data.replace(/(^|[^A-Za-z])(Zos Shivros Channel)(?=[^A-Za-z]|$)/gi, '$1山吉之街');
data=data.replace(/(^|[^A-Za-z])(Nahpui Quarter)(?=[^A-Za-z]|$)/gi, '$1纳普区');
data=data.replace(/(^|[^A-Za-z])(Nahpui Quarter)(?=[^A-Za-z]|$)/gi, '$1纳普区主线');
data=data.replace(/(^|[^A-Za-z])(Essence of Dragon)(?=[^A-Za-z]|$)/gi, '$1龙之质体');
data=data.replace(/(^|[^A-Za-z])(Essence of Kirin)(?=[^A-Za-z]|$)/gi, '$1麒麟之质体');
data=data.replace(/(^|[^A-Za-z])(Essence of Phoenix)(?=[^A-Za-z]|$)/gi, '$1凤之质体');
data=data.replace(/(^|[^A-Za-z])(Essence of Turtle)(?=[^A-Za-z]|$)/gi, '$1龟之质体');
data=data.replace(/(^|[^A-Za-z])(Celestial Essence)(?=[^A-Za-z]|$)/gi, '$1天神质体');
data=data.replace(/(^|[^A-Za-z])(The Granite Citadel)(?=[^A-Za-z]|$)/gi, '$1花岗岩堡垒');
data=data.replace(/(^|[^A-Za-z])(Spearhead Peak)(?=[^A-Za-z]|$)/gi, '$1尖枪山');
data=data.replace(/(^|[^A-Za-z])(Ice Imp)(?=[^A-Za-z]|$)/gi, '$1冰小恶魔');
data=data.replace(/(^|[^A-Za-z])(Frigid Heart)(?=[^A-Za-z]|$)/gi, '$1冰冻的心脏');
data=data.replace(/(^|[^A-Za-z])(Thirsty River)(?=[^A-Za-z]|$)/gi, '$1干枯河流');
data=data.replace(/(^|[^A-Za-z])(The Scar)(?=[^A-Za-z]|$)/gi, '$1断崖');
data=data.replace(/(^|[^A-Za-z])(Destiny's Gorge)(?=[^A-Za-z]|$)/gi, '$1命运峡谷');
data=data.replace(/(^|[^A-Za-z])(Augury Rock)(?=[^A-Za-z]|$)/gi, '$1占卜之石');
data=data.replace(/(^|[^A-Za-z])(Skyward Reach)(?=[^A-Za-z]|$)/gi, '$1天际流域');
data=data.replace(/(^|[^A-Za-z])(Hydra)(?=[^A-Za-z]|$)/gi, '$1三头龙');
data=data.replace(/(^|[^A-Za-z])(Dessicated Hydra Claw)(?=[^A-Za-z]|$)/gi, '$1干燥的三头龙爪');
data=data.replace(/(^|[^A-Za-z])(Umbral Grotto)(?=[^A-Za-z]|$)/gi, '$1阴影石穴');
data=data.replace(/(^|[^A-Za-z])(Verdant Cascades)(?=[^A-Za-z]|$)/gi, '$1远野瀑布');
data=data.replace(/(^|[^A-Za-z])(Skelk Reaper)(?=[^A-Za-z]|$)/gi, '$1司怪收割者');
data=data.replace(/(^|[^A-Za-z])(Skelk Scourger)(?=[^A-Za-z]|$)/gi, '$1司怪严惩者');
data=data.replace(/(^|[^A-Za-z])(Skelk Afflictor)(?=[^A-Za-z]|$)/gi, '$1司怪折磨者');
data=data.replace(/(^|[^A-Za-z])(Skelk Claw)(?=[^A-Za-z]|$)/gi, '$1司怪爪');
data=data.replace(/(^|[^A-Za-z])(Vasburg Armory)(?=[^A-Za-z]|$)/gi, '$1维思柏兵营');
data=data.replace(/(^|[^A-Za-z])(Morostav Trail)(?=[^A-Za-z]|$)/gi, '$1摩洛神秘通道');
data=data.replace(/(^|[^A-Za-z])(Durheim Archives)(?=[^A-Za-z]|$)/gi, '$1杜汉姆卷藏室');
data=data.replace(/(^|[^A-Za-z])(Fungal Wallow)(?=[^A-Za-z]|$)/gi, '$1泥泞兽');
data=data.replace(/(^|[^A-Za-z])(Truffle)(?=[^A-Za-z]|$)/gi, '$1松露');
data=data.replace(/(^|[^A-Za-z])(Kodlonu Hamlet)(?=[^A-Za-z]|$)/gi, '$1克拓奴 哈姆雷特');
data=data.replace(/(^|[^A-Za-z])(Mehtani Keys)(?=[^A-Za-z]|$)/gi, '$1梅坦尼之钥');
data=data.replace(/(^|[^A-Za-z])(Corsair)(?=[^A-Za-z]|$)/gi, '$1海盗');
data=data.replace(/(^|[^A-Za-z])(Silver Bullion Coin)(?=[^A-Za-z]|$)/gi, '$1银铸币');
data=data.replace(/(^|[^A-Za-z])(Camp Rankor)(?=[^A-Za-z]|$)/gi, '$1蓝口营地');
data=data.replace(/(^|[^A-Za-z])(Snake Dance)(?=[^A-Za-z]|$)/gi, '$1蛇舞');
data=data.replace(/(^|[^A-Za-z])(Blessed Griffon)(?=[^A-Za-z]|$)/gi, '$1被祝福的狮鹫兽');
data=data.replace(/(^|[^A-Za-z])(Frosted Griffon Wing)(?=[^A-Za-z]|$)/gi, '$1冻结的狮鹫兽翅膀');
data=data.replace(/(^|[^A-Za-z])(Augury Rock)(?=[^A-Za-z]|$)/gi, '$1占卜之石');
data=data.replace(/(^|[^A-Za-z])(Prophet's Path)(?=[^A-Za-z]|$)/gi, '$1先知之路');
data=data.replace(/(^|[^A-Za-z])(Minotaur (Crystal Desert))(?=[^A-Za-z]|$)/gi, '$1牛头怪');
data=data.replace(/(^|[^A-Za-z])(Minotaur Horn)(?=[^A-Za-z]|$)/gi, '$1牛头怪角');
data=data.replace(/(^|[^A-Za-z])(Zin Ku Corridor)(?=[^A-Za-z]|$)/gi, '$1辛库走廊');
data=data.replace(/(^|[^A-Za-z])(Tahnnakai Temple)(?=[^A-Za-z]|$)/gi, '$1谭纳凯神殿探索区');
data=data.replace(/(^|[^A-Za-z])(Jade Brotherhood)(?=[^A-Za-z]|$)/gi, '$1翡翠兄弟会');
data=data.replace(/(^|[^A-Za-z])(Jade Bracelet)(?=[^A-Za-z]|$)/gi, '$1翡翠手镯');
data=data.replace(/(^|[^A-Za-z])(Zen Daijun)(?=[^A-Za-z]|$)/gi, '$1祯台郡');
data=data.replace(/(^|[^A-Za-z])(Haiju Lagoon)(?=[^A-Za-z]|$)/gi, '$1海幽泻湖');
data=data.replace(/(^|[^A-Za-z])(Crimson Skull Spirit Lord)(?=[^A-Za-z]|$)/gi, '$1红颅灵王');
data=data.replace(/(^|[^A-Za-z])(Crimson Skull Longbow)(?=[^A-Za-z]|$)/gi, '$1红颅长弓手');
data=data.replace(/(^|[^A-Za-z])(Crimson Skull Mentalist)(?=[^A-Za-z]|$)/gi, '$1红颅心灵使');
data=data.replace(/(^|[^A-Za-z])(Crimson Skull Priest)(?=[^A-Za-z]|$)/gi, '$1红颅祭司');
data=data.replace(/(^|[^A-Za-z])(Gold Crimson Skull Coin)(?=[^A-Za-z]|$)/gi, '$1红颅金币');
data=data.replace(/(^|[^A-Za-z])(Mihanu Township)(?=[^A-Za-z]|$)/gi, '$1米哈努小镇');
data=data.replace(/(^|[^A-Za-z])(Holdings of Chokhin)(?=[^A-Za-z]|$)/gi, '$1舟克辛卷藏室');
data=data.replace(/(^|[^A-Za-z])(Bull Trainer Giant)(?=[^A-Za-z]|$)/gi, '$1Bull Trainer Giant');
data=data.replace(/(^|[^A-Za-z])(Pillaged Goods)(?=[^A-Za-z]|$)/gi, '$1掠夺的货品');
data=data.replace(/(^|[^A-Za-z])(Lion's Arch)(?=[^A-Za-z]|$)/gi, '$1狮子拱门');
data=data.replace(/(^|[^A-Za-z])(North Kryta Province)(?=[^A-Za-z]|$)/gi, '$1科瑞塔北部');
data=data.replace(/(^|[^A-Za-z])(Caromi Tengu Brave)(?=[^A-Za-z]|$)/gi, '$1卡洛米天狗勇士');
data=data.replace(/(^|[^A-Za-z])(Caromi Tengu Wild)(?=[^A-Za-z]|$)/gi, '$1卡洛米天狗野人');
data=data.replace(/(^|[^A-Za-z])(Caromi Tengu Scout)(?=[^A-Za-z]|$)/gi, '$1卡洛米天狗射手');
data=data.replace(/(^|[^A-Za-z])(Feathered Caromi Scalp)(?=[^A-Za-z]|$)/gi, '$1卡洛米羽毛头皮');
data=data.replace(/(^|[^A-Za-z])(Altrumm Ruins)(?=[^A-Za-z]|$)/gi, '$1奥楚兰废墟');
data=data.replace(/(^|[^A-Za-z])(Arborstone)(?=[^A-Za-z]|$)/gi, '$1亭石探索区');
data=data.replace(/(^|[^A-Za-z])(Arborstone)(?=[^A-Za-z]|$)/gi, '$1亭石主线');
data=data.replace(/(^|[^A-Za-z])(Vasburg Armory)(?=[^A-Za-z]|$)/gi, '$1维思柏兵营');
data=data.replace(/(^|[^A-Za-z])(Morostav Trail)(?=[^A-Za-z]|$)/gi, '$1摩洛神秘通道');
data=data.replace(/(^|[^A-Za-z])(Stone Reaper)(?=[^A-Za-z]|$)/gi, '$1石之收割者');
data=data.replace(/(^|[^A-Za-z])(Stone Rain)(?=[^A-Za-z]|$)/gi, '$1石之雨');
data=data.replace(/(^|[^A-Za-z])(Stone Soul)(?=[^A-Za-z]|$)/gi, '$1石之灵');
data=data.replace(/(^|[^A-Za-z])(Stone Carving)(?=[^A-Za-z]|$)/gi, '$1石雕品');
data=data.replace(/(^|[^A-Za-z])(Honur Hill)(?=[^A-Za-z]|$)/gi, '$1霍奴尔丘陵');
data=data.replace(/(^|[^A-Za-z])(Resplendent Makuun)(?=[^A-Za-z]|$)/gi, '$1奢华之城．莫肯');
data=data.replace(/(^|[^A-Za-z])(Dasha Vestibule)(?=[^A-Za-z]|$)/gi, '$1达沙走廊');
data=data.replace(/(^|[^A-Za-z])(Key of Ahdashim)(?=[^A-Za-z]|$)/gi, '$1哈达辛之钥');
data=data.replace(/(^|[^A-Za-z])(The Hidden City of Ahdashim)(?=[^A-Za-z]|$)/gi, '$1隐藏之城．哈达辛');
data=data.replace(/(^|[^A-Za-z])(Sapphire Djinn)(?=[^A-Za-z]|$)/gi, '$1蓝宝石巨灵');
data=data.replace(/(^|[^A-Za-z])(Sapphire Djinn Essence)(?=[^A-Za-z]|$)/gi, '$1蓝宝石巨灵精华');
data=data.replace(/(^|[^A-Za-z])(Henge of Denravi)(?=[^A-Za-z]|$)/gi, '$1丹拉维圣地');
data=data.replace(/(^|[^A-Za-z])(Tangle Root)(?=[^A-Za-z]|$)/gi, '$1纠结之恨');
data=data.replace(/(^|[^A-Za-z])(Jungle Troll)(?=[^A-Za-z]|$)/gi, '$1丛林巨魔');
data=data.replace(/(^|[^A-Za-z])(Jungle Troll Tusk)(?=[^A-Za-z]|$)/gi, '$1丛林巨魔獠牙');
data=data.replace(/(^|[^A-Za-z])(Wehhan Terraces)(?=[^A-Za-z]|$)/gi, '$1薇恩平台');
data=data.replace(/(^|[^A-Za-z])(Bahdok Caverns)(?=[^A-Za-z]|$)/gi, '$1巴多克洞穴');
data=data.replace(/(^|[^A-Za-z])(Pogahn Passage)(?=[^A-Za-z]|$)/gi, '$1波甘驿站');
data=data.replace(/(^|[^A-Za-z])(Dejarin Estate)(?=[^A-Za-z]|$)/gi, '$1达贾林庄园');
data=data.replace(/(^|[^A-Za-z])(Cracked Mesa)(?=[^A-Za-z]|$)/gi, '$1疯狂梅萨');
data=data.replace(/(^|[^A-Za-z])(Stone Shard Crag)(?=[^A-Za-z]|$)/gi, '$1巨大岩石怪');
data=data.replace(/(^|[^A-Za-z])(Sentient Lodestone)(?=[^A-Za-z]|$)/gi, '$1知觉磁石');
data=data.replace(/(^|[^A-Za-z])(Marhan's Grotto)(?=[^A-Za-z]|$)/gi, '$1马翰洞穴');
data=data.replace(/(^|[^A-Za-z])(Ice Floe)(?=[^A-Za-z]|$)/gi, '$1浮冰');
data=data.replace(/(^|[^A-Za-z])(Thunderhead Keep)(?=[^A-Za-z]|$)/gi, '$1雷云要塞');
data=data.replace(/(^|[^A-Za-z])(Mursaat)(?=[^A-Za-z]|$)/gi, '$1马赛特');
data=data.replace(/(^|[^A-Za-z])(Mursaat Token)(?=[^A-Za-z]|$)/gi, '$1马赛特记号');
data=data.replace(/(^|[^A-Za-z])(Eye of the North)(?=[^A-Za-z]|$)/gi, '$1极地之眼');
data=data.replace(/(^|[^A-Za-z])(Ice Cliff Chasms)(?=[^A-Za-z]|$)/gi, '$1冰崖裂口');
data=data.replace(/(^|[^A-Za-z])(Gwen's garden)(?=[^A-Za-z]|$)/gi, '$1关的庭园');
data=data.replace(/(^|[^A-Za-z])(Battledepths)(?=[^A-Za-z]|$)/gi, '$1战斗深渊');
data=data.replace(/(^|[^A-Za-z])(Chromatic Drake)(?=[^A-Za-z]|$)/gi, '$1染色龙兽');
data=data.replace(/(^|[^A-Za-z])(Chromatic Sc​​ale)(?=[^A-Za-z]|$)/gi, '$1染色的麟片');
data=data.replace(/(^|[^A-Za-z])(Augury Rock)(?=[^A-Za-z]|$)/gi, '$1占卜之石');
data=data.replace(/(^|[^A-Za-z])(The Arid Sea)(?=[^A-Za-z]|$)/gi, '$1枯竭之海');
data=data.replace(/(^|[^A-Za-z])(Dunes of Despair)(?=[^A-Za-z]|$)/gi, '$1绝望沙丘');
data=data.replace(/(^|[^A-Za-z])(Sand Giant)(?=[^A-Za-z]|$)/gi, '$1沙巨人');
data=data.replace(/(^|[^A-Za-z])(Massive Jawbone)(?=[^A-Za-z]|$)/gi, '$1粗大下颚骨');
data=data.replace(/(^|[^A-Za-z])(Leviathan Pits)(?=[^A-Za-z]|$)/gi, '$1利拜亚森矿场');
data=data.replace(/(^|[^A-Za-z])(Gyala Hatchery)(?=[^A-Za-z]|$)/gi, '$1盖拉孵化所探索区');
data=data.replace(/(^|[^A-Za-z])(Leviathan Claw)(?=[^A-Za-z]|$)/gi, '$1利拜亚森之爪');
data=data.replace(/(^|[^A-Za-z])(Leviathan Eye)(?=[^A-Za-z]|$)/gi, '$1利拜亚森之眼');
data=data.replace(/(^|[^A-Za-z])(Leviathan Mouth)(?=[^A-Za-z]|$)/gi, '$1利拜亚森之口');
data=data.replace(/(^|[^A-Za-z])(Moon Shell)(?=[^A-Za-z]|$)/gi, '$1月贝');
data=data.replace(/(^|[^A-Za-z])(Frontier Gate)(?=[^A-Za-z]|$)/gi, '$1边境关所');
data=data.replace(/(^|[^A-Za-z])(Eastern Frontier)(?=[^A-Za-z]|$)/gi, '$1东方边境');
data=data.replace(/(^|[^A-Za-z])(Carrion Devourer)(?=[^A-Za-z]|$)/gi, '$1腐肉蝎');
data=data.replace(/(^|[^A-Za-z])(Whiptail Devourer)(?=[^A-Za-z]|$)/gi, '$1鞭尾蝎');
data=data.replace(/(^|[^A-Za-z])(Plague Devourer)(?=[^A-Za-z]|$)/gi, '$1瘟疫蝎');
data=data.replace(/(^|[^A-Za-z])(Fetid Carapace)(?=[^A-Za-z]|$)/gi, '$1恶臭的甲壳');
data=data.replace(/(^|[^A-Za-z])(Beacon's Perch)(?=[^A-Za-z]|$)/gi, '$1毕肯高地');
data=data.replace(/(^|[^A-Za-z])(Deldrimor Bowl)(?=[^A-Za-z]|$)/gi, '$1戴尔狄摩盆地');
data=data.replace(/(^|[^A-Za-z])(Shiverpeak Warrior)(?=[^A-Za-z]|$)/gi, '$1席娃山脉战士');
data=data.replace(/(^|[^A-Za-z])(Shiverpeak Longbow)(?=[^A-Za-z]|$)/gi, '$1席娃山脉弓手');
data=data.replace(/(^|[^A-Za-z])(Shiverpeak Protector)(?=[^A-Za-z]|$)/gi, '$1席娃山脉守护者');
data=data.replace(/(^|[^A-Za-z])(Shiverpeak Mane)(?=[^A-Za-z]|$)/gi, '$1席娃山脉鬃毛');
data=data.replace(/(^|[^A-Za-z])(The Marketplace)(?=[^A-Za-z]|$)/gi, '$1市集');
data=data.replace(/(^|[^A-Za-z])(Bukdek Byway)(?=[^A-Za-z]|$)/gi, '$1巴德克小径');
data=data.replace(/(^|[^A-Za-z])(Branches of Juni Berries)(?=[^A-Za-z]|$)/gi, '$1柳树枝');
data=data.replace(/(^|[^A-Za-z])(Sunspear Sanctuary)(?=[^A-Za-z]|$)/gi, '$1日戟避难所');
data=data.replace(/(^|[^A-Za-z])(Marga Coast)(?=[^A-Za-z]|$)/gi, '$1马加海岸');
data=data.replace(/(^|[^A-Za-z])(Ronjok)(?=[^A-Za-z]|$)/gi, '$1罗鸠村');
data=data.replace(/(^|[^A-Za-z])(Chuno)(?=[^A-Za-z]|$)/gi, '$1周纳');
data=data.replace(/(^|[^A-Za-z])(Insatiable Appetite)(?=[^A-Za-z]|$)/gi, '$1贪得无厌的食欲');
data=data.replace(/(^|[^A-Za-z])(Toma)(?=[^A-Za-z]|$)/gi, '$1托玛');
data=data.replace(/(^|[^A-Za-z])(Tihark Orchard)(?=[^A-Za-z]|$)/gi, '$1提亚克林地');
data=data.replace(/(^|[^A-Za-z])(Garden of Seborhin)(?=[^A-Za-z]|$)/gi, '$1希伯欣花园');
data=data.replace(/(^|[^A-Za-z])(Forum Highlands)(?=[^A-Za-z]|$)/gi, '$1高地广场');
data=data.replace(/(^|[^A-Za-z])(Roaring Ether)(?=[^A-Za-z]|$)/gi, '$1苍穹咆哮者');
data=data.replace(/(^|[^A-Za-z])(Roaring Ether Claw)(?=[^A-Za-z]|$)/gi, '$1苍穹咆哮者之爪');
data=data.replace(/(^|[^A-Za-z])(Seitung Harbor)(?=[^A-Za-z]|$)/gi, '$1青函港');
data=data.replace(/(^|[^A-Za-z])(Zen Daijun)(?=[^A-Za-z]|$)/gi, '$1祯邰郡探索区');
data=data.replace(/(^|[^A-Za-z])(Roll of Parchment)(?=[^A-Za-z]|$)/gi, '$1羊皮纸卷');
data=data.replace(/(^|[^A-Za-z])(Kaineng Center)(?=[^A-Za-z]|$)/gi, '$1凯宁中心');
data=data.replace(/(^|[^A-Za-z])(Xue Yi)(?=[^A-Za-z]|$)/gi, '$1薛易');
data=data.replace(/(^|[^A-Za-z])(Wood Plank)(?=[^A-Za-z]|$)/gi, '$1树木');
data=data.replace(/(^|[^A-Za-z])(Roll of Parchment)(?=[^A-Za-z]|$)/gi, '$1羊皮纸卷');
data=data.replace(/(^|[^A-Za-z])(Doomlore Shrine)(?=[^A-Za-z]|$)/gi, '$1末日传说神殿');
data=data.replace(/(^|[^A-Za-z])(Dalada Uplands)(?=[^A-Za-z]|$)/gi, '$1达拉达山地');
data=data.replace(/(^|[^A-Za-z])(Charr Seeker)(?=[^A-Za-z]|$)/gi, '$1夏尔追寻者');
data=data.replace(/(^|[^A-Za-z])(Charr Blademaster)(?=[^A-Za-z]|$)/gi, '$1夏尔剑术大师');
data=data.replace(/(^|[^A-Za-z])(Charr Prophet)(?=[^A-Za-z]|$)/gi, '$1夏尔先知');
data=data.replace(/(^|[^A-Za-z])(Charr Flameshielder)(?=[^A-Za-z]|$)/gi, '$1夏尔避燃者');
data=data.replace(/(^|[^A-Za-z])(Superb Charr Carving)(?=[^A-Za-z]|$)/gi, '$1超级夏尔雕刻品');
data=data.replace(/(^|[^A-Za-z])(Olafstead)(?=[^A-Za-z]|$)/gi, '$1欧拉夫之地');
data=data.replace(/(^|[^A-Za-z])(Varajar Fells)(?=[^A-Za-z]|$)/gi, '$1维拉戛阵地');
data=data.replace(/(^|[^A-Za-z])(Modniir Berserker)(?=[^A-Za-z]|$)/gi, '$1莫得米狂战士');
data=data.replace(/(^|[^A-Za-z])(Modniir Hunter)(?=[^A-Za-z]|$)/gi, '$1莫得米猎人');
data=data.replace(/(^|[^A-Za-z])(Modniir Mane)(?=[^A-Za-z]|$)/gi, '$1莫得米鬃毛');
data=data.replace(/(^|[^A-Za-z])(Leviathan Pits)(?=[^A-Za-z]|$)/gi, '$1利拜亚森矿场');
data=data.replace(/(^|[^A-Za-z])(Rhea's Crater)(?=[^A-Za-z]|$)/gi, '$1席亚火山口');
data=data.replace(/(^|[^A-Za-z])(Outcast Warrior)(?=[^A-Za-z]|$)/gi, '$1被流放的战士');
data=data.replace(/(^|[^A-Za-z])(Outcast Assassin)(?=[^A-Za-z]|$)/gi, '$1被流放的暗杀者');
data=data.replace(/(^|[^A-Za-z])(Outcast Ritualist)(?=[^A-Za-z]|$)/gi, '$1被流放的祭祀者');
data=data.replace(/(^|[^A-Za-z])(Majesty's Rest)(?=[^A-Za-z]|$)/gi, '$1王者安息地');
data=data.replace(/(^|[^A-Za-z])(Druid's Overlook)(?=[^A-Za-z]|$)/gi, '$1德鲁伊高地');
data=data.replace(/(^|[^A-Za-z])(Temple of the Ages)(?=[^A-Za-z]|$)/gi, '$1世纪神殿');
data=data.replace(/(^|[^A-Za-z])(Thorn Devourer)(?=[^A-Za-z]|$)/gi, '$1棘刺蝎');
data=data.replace(/(^|[^A-Za-z])(Fevered Devourer)(?=[^A-Za-z]|$)/gi, '$1热病蝎');
data=data.replace(/(^|[^A-Za-z])(Thorny Carapace)(?=[^A-Za-z]|$)/gi, '$1多刺的甲壳');
data=data.replace(/(^|[^A-Za-z])(Bone Palace)(?=[^A-Za-z]|$)/gi, '$1白骨宫殿');
data=data.replace(/(^|[^A-Za-z])(The Alkali Pan)(?=[^A-Za-z]|$)/gi, '$1金属熔炉');
data=data.replace(/(^|[^A-Za-z])(Ruby Djinn)(?=[^A-Za-z]|$)/gi, '$1红宝石巨灵');
data=data.replace(/(^|[^A-Za-z])(Ruby Djinn Essence)(?=[^A-Za-z]|$)/gi, '$1红宝石巨灵精华');
data=data.replace(/(^|[^A-Za-z])(Piken Square)(?=[^A-Za-z]|$)/gi, '$1派肯广场');
data=data.replace(/(^|[^A-Za-z])(The Breach)(?=[^A-Za-z]|$)/gi, '$1缺口');
data=data.replace(/(^|[^A-Za-z])(Ascalon)(?=[^A-Za-z]|$)/gi, '$1阿斯卡隆');
data=data.replace(/(^|[^A-Za-z])(Charr)(?=[^A-Za-z]|$)/gi, '$1夏尔');
data=data.replace(/(^|[^A-Za-z])(Charr Hide)(?=[^A-Za-z]|$)/gi, '$1夏尔皮');
data=data.replace(/(^|[^A-Za-z])(Ventari's Refuge)(?=[^A-Za-z]|$)/gi, '$1凡特里庇护所');
data=data.replace(/(^|[^A-Za-z])(The Falls)(?=[^A-Za-z]|$)/gi, '$1陷落区');
data=data.replace(/(^|[^A-Za-z])(The Fissure of Woe)(?=[^A-Za-z]|$)/gi, '$1灾难裂痕');
data=data.replace(/(^|[^A-Za-z])(Forest of the Wailing Lord)(?=[^A-Za-z]|$)/gi, '$1悲鸣领主区');
data=data.replace(/(^|[^A-Za-z])(Gloom Seed)(?=[^A-Za-z]|$)/gi, '$1黑暗种子');
data=data.replace(/(^|[^A-Za-z])(Breaker Hollow)(?=[^A-Za-z]|$)/gi, '$1断崖谷');
data=data.replace(/(^|[^A-Za-z])(Mount Qinkai)(?=[^A-Za-z]|$)/gi, '$1今凯山');
data=data.replace(/(^|[^A-Za-z])(Naga Warrior)(?=[^A-Za-z]|$)/gi, '$1迦纳战士');
data=data.replace(/(^|[^A-Za-z])(Naga Archer)(?=[^A-Za-z]|$)/gi, '$1迦纳弓手');
data=data.replace(/(^|[^A-Za-z])(Naga Ritualist)(?=[^A-Za-z]|$)/gi, '$1迦纳祭祀者');
data=data.replace(/(^|[^A-Za-z])(Naga Skin)(?=[^A-Za-z]|$)/gi, '$1迦纳外皮');
data=data.replace(/(^|[^A-Za-z])(Riverside Province)(?=[^A-Za-z]|$)/gi, '$1河畔地带');
data=data.replace(/(^|[^A-Za-z])(Twin Serpent Lakes)(?=[^A-Za-z]|$)/gi, '$1双头蛇湖泊');
data=data.replace(/(^|[^A-Za-z])(Lion's Arch)(?=[^A-Za-z]|$)/gi, '$1狮子拱门');
data=data.replace(/(^|[^A-Za-z])(Bog Skale)(?=[^A-Za-z]|$)/gi, '$1泥鳞怪');
data=data.replace(/(^|[^A-Za-z])(Twin Serpent Lakes)(?=[^A-Za-z]|$)/gi, '$1双头蛇湖泊');
data=data.replace(/(^|[^A-Za-z])(Gruhn the Fisher)(?=[^A-Za-z]|$)/gi, '$1渔人古露恩');
data=data.replace(/(^|[^A-Za-z])(Bog Skale Fin)(?=[^A-Za-z]|$)/gi, '$1泥鳞怪的鳍');
data=data.replace(/(^|[^A-Za-z])(Herring)(?=[^A-Za-z]|$)/gi, '$1鲱鱼');
data=data.replace(/(^|[^A-Za-z])(Doomlore Shrine)(?=[^A-Za-z]|$)/gi, '$1末日传说神殿');
data=data.replace(/(^|[^A-Za-z])(Sacnoth Valley)(?=[^A-Za-z]|$)/gi, '$1圣诺谷');
data=data.replace(/(^|[^A-Za-z])(Grawl Champion)(?=[^A-Za-z]|$)/gi, '$1穴居人冠军');
data=data.replace(/(^|[^A-Za-z])(Grawl Dark Priest)(?=[^A-Za-z]|$)/gi, '$1穴居人黑暗祭司');
data=data.replace(/(^|[^A-Za-z])(Stone Grawl Necklace)(?=[^A-Za-z]|$)/gi, '$1石穴居人项链');
data=data.replace(/(^|[^A-Za-z])(Jokanur Diggings)(?=[^A-Za-z]|$)/gi, '$1卓坎诺挖掘点');
data=data.replace(/(^|[^A-Za-z])(Fahranur, The First City)(?=[^A-Za-z]|$)/gi, '$1旧城 法兰努尔');
data=data.replace(/(^|[^A-Za-z])(Beautiful Iboga)(?=[^A-Za-z]|$)/gi, '$1美丽伊波枷');
data=data.replace(/(^|[^A-Za-z])(Fanged Iboga)(?=[^A-Za-z]|$)/gi, '$1毒牙伊波枷');
data=data.replace(/(^|[^A-Za-z])(Sentient Seed)(?=[^A-Za-z]|$)/gi, '$1知觉种子');
data=data.replace(/(^|[^A-Za-z])(Seitung Harbor)(?=[^A-Za-z]|$)/gi, '$1青函港');
data=data.replace(/(^|[^A-Za-z])(Saoshang Trail)(?=[^A-Za-z]|$)/gi, '$1绍商小径');
data=data.replace(/(^|[^A-Za-z])(Mantid Darkwing)(?=[^A-Za-z]|$)/gi, '$1螳螂黑翼');
data=data.replace(/(^|[^A-Za-z])(Mantid Glitterfang)(?=[^A-Za-z]|$)/gi, '$1螳螂锐牙');
data=data.replace(/(^|[^A-Za-z])(Mantid Pincer)(?=[^A-Za-z]|$)/gi, '$1螳螂镰');
data=data.replace(/(^|[^A-Za-z])(Ember Light Camp)(?=[^A-Za-z]|$)/gi, '$1残火营地');
data=data.replace(/(^|[^A-Za-z])(Perdition Rock)(?=[^A-Za-z]|$)/gi, '$1破灭石');
data=data.replace(/(^|[^A-Za-z])(Mahgo Hydra)(?=[^A-Za-z]|$)/gi, '$1码果三头龙');
data=data.replace(/(^|[^A-Za-z])(Mahgo Claw)(?=[^A-Za-z]|$)/gi, '$1码果的爪');
data=data.replace(/(^|[^A-Za-z])(Yohlon Haven)(?=[^A-Za-z]|$)/gi, '$1犹朗避难所');
data=data.replace(/(^|[^A-Za-z])(Arkjok Ward)(?=[^A-Za-z]|$)/gi, '$1阿尔科监禁区');
data=data.replace(/(^|[^A-Za-z])(Mandragor Imp)(?=[^A-Za-z]|$)/gi, '$1曼陀罗恶魔');
data=data.replace(/(^|[^A-Za-z])(Mandragor Slither)(?=[^A-Za-z]|$)/gi, '$1曼陀罗撕裂者');
data=data.replace(/(^|[^A-Za-z])(Mandragor Root)(?=[^A-Za-z]|$)/gi, '$1曼陀罗根');
data=data.replace(/(^|[^A-Za-z])(Yohlon Haven)(?=[^A-Za-z]|$)/gi, '$1犹朗避难所');
data=data.replace(/(^|[^A-Za-z])(Yajide)(?=[^A-Za-z]|$)/gi, '$1叶吉达');
data=data.replace(/(^|[^A-Za-z])(Mandragor Root)(?=[^A-Za-z]|$)/gi, '$1曼陀罗根');
data=data.replace(/(^|[^A-Za-z])(Mandragor Root Cake)(?=[^A-Za-z]|$)/gi, '$1曼陀罗根糕点');
data=data.replace(/(^|[^A-Za-z])(Snake Dance)(?=[^A-Za-z]|$)/gi, '$1蛇舞');
data=data.replace(/(^|[^A-Za-z])(Dreadnought's Drift)(?=[^A-Za-z]|$)/gi, '$1无惧者之丘');
data=data.replace(/(^|[^A-Za-z])(Beacon's Perch)(?=[^A-Za-z]|$)/gi, '$1毕肯高地');
data=data.replace(/(^|[^A-Za-z])(Deldrimor War Camp)(?=[^A-Za-z]|$)/gi, '$1戴尔狄摩兵营');
data=data.replace(/(^|[^A-Za-z])(Azure Shadow)(?=[^A-Za-z]|$)/gi, '$1湛蓝阴影');
data=data.replace(/(^|[^A-Za-z])(Azure Remain)(?=[^A-Za-z]|$)/gi, '$1湛蓝残留物');
data=data.replace(/(^|[^A-Za-z])(The Marketplace)(?=[^A-Za-z]|$)/gi, '$1市集');
data=data.replace(/(^|[^A-Za-z])(Wajjun Bazaar)(?=[^A-Za-z]|$)/gi, '$1瓦江市场');
data=data.replace(/(^|[^A-Za-z])(Am Fah)(?=[^A-Za-z]|$)/gi, '$1安费');
data=data.replace(/(^|[^A-Za-z])(Plague Idol)(?=[^A-Za-z]|$)/gi, '$1瘟疫法器');
data=data.replace(/(^|[^A-Za-z])(Tarnished Haven)(?=[^A-Za-z]|$)/gi, '$1灰暗避难所');
data=data.replace(/(^|[^A-Za-z])(Alcazia Tangle)(?=[^A-Za-z]|$)/gi, '$1纠结之艾卡滋亚');
data=data.replace(/(^|[^A-Za-z])(Umbral Grotto)(?=[^A-Za-z]|$)/gi, '$1阴影石穴');
data=data.replace(/(^|[^A-Za-z])(Verdant Cascades)(?=[^A-Za-z]|$)/gi, '$1原野瀑布');
data=data.replace(/(^|[^A-Za-z])(Quetzal)(?=[^A-Za-z]|$)/gi, '$1长尾');
data=data.replace(/(^|[^A-Za-z])(Quetzal Crests)(?=[^A-Za-z]|$)/gi, '$1长尾冠毛');
data=data.replace(/(^|[^A-Za-z])(The Mouth of Torment)(?=[^A-Za-z]|$)/gi, '$1苦痛之地隘口');
data=data.replace(/(^|[^A-Za-z])(Poisoned Outcrops)(?=[^A-Za-z]|$)/gi, '$1剧毒地表');
data=data.replace(/(^|[^A-Za-z])(Margonite)(?=[^A-Za-z]|$)/gi, '$1玛骨奈');
data=data.replace(/(^|[^A-Za-z])(Margonite Mask)(?=[^A-Za-z]|$)/gi, '$1玛骨奈面具');
data=data.replace(/(^|[^A-Za-z])(The Granite Citadel)(?=[^A-Za-z]|$)/gi, '$1花岗岩堡垒');
data=data.replace(/(^|[^A-Za-z])(Tasca's Demise)(?=[^A-Za-z]|$)/gi, '$1塔斯加之死');
data=data.replace(/(^|[^A-Za-z])(Mineral Springs)(?=[^A-Za-z]|$)/gi, '$1矿物泉源');
data=data.replace(/(^|[^A-Za-z])(Tengu)(?=[^A-Za-z]|$)/gi, '$1天狗');
data=data.replace(/(^|[^A-Za-z])(Avicara)(?=[^A-Za-z]|$)/gi, '$1阿比卡拉');
data=data.replace(/(^|[^A-Za-z])(Feathered Avicara Scalp)(?=[^A-Za-z]|$)/gi, '$1阿比卡拉头皮羽毛');
data=data.replace(/(^|[^A-Za-z])(Fort Ranik)(?=[^A-Za-z]|$)/gi, '$1瑞尼克要塞');
data=data.replace(/(^|[^A-Za-z])(Regent Valley)(?=[^A-Za-z]|$)/gi, '$1统治者之谷');
data=data.replace(/(^|[^A-Za-z])(Red Iris Flower)(?=[^A-Za-z]|$)/gi, '$1红色鸢尾花');
data=data.replace(/(^|[^A-Za-z])(Grendich Courthouse)(?=[^A-Za-z]|$)/gi, '$1葛兰迪法院');
data=data.replace(/(^|[^A-Za-z])(Flame Temple Corridor)(?=[^A-Za-z]|$)/gi, '$1夏尔火焰神殿');
data=data.replace(/(^|[^A-Za-z])(Charr)(?=[^A-Za-z]|$)/gi, '$1夏尔');
data=data.replace(/(^|[^A-Za-z])(Charr Carving)(?=[^A-Za-z]|$)/gi, '$1夏尔雕刻品');
data=data.replace(/(^|[^A-Za-z])(Yak's Bend)(?=[^A-Za-z]|$)/gi, '$1牦牛村');
data=data.replace(/(^|[^A-Za-z])(Traveler's Vale)(?=[^A-Za-z]|$)/gi, '$1旅人谷');
data=data.replace(/(^|[^A-Za-z])(Rare material trader)(?=[^A-Za-z]|$)/gi, '$1稀有材料商人');
data=data.replace(/(^|[^A-Za-z])(Bolt of Linen)(?=[^A-Za-z]|$)/gi, '$1亚麻布');
data=data.replace(/(^|[^A-Za-z])(Artisan)(?=[^A-Za-z]|$)/gi, '$1工匠');
data=data.replace(/(^|[^A-Za-z])(Plant Fiber)(?=[^A-Za-z]|$)/gi, '$1植物纤维');
data=data.replace(/(^|[^A-Za-z])(Gunnar's Hold)(?=[^A-Za-z]|$)/gi, '$1甘拿的占领地');
data=data.replace(/(^|[^A-Za-z])(Norrhart Domains)(?=[^A-Za-z]|$)/gi, '$1诺恩之心领地');
data=data.replace(/(^|[^A-Za-z])(Dreamroot Mandragor)(?=[^A-Za-z]|$)/gi, '$1梦之根曼陀罗');
data=data.replace(/(^|[^A-Za-z])(Mandragor Scavenger)(?=[^A-Za-z]|$)/gi, '$1拾荒曼陀罗');
data=data.replace(/(^|[^A-Za-z])(Mystic Mandragor)(?=[^A-Za-z]|$)/gi, '$1秘教曼陀罗');
data=data.replace(/(^|[^A-Za-z])(Ulcerous Mandragor)(?=[^A-Za-z]|$)/gi, '$1已腐蚀曼陀罗');
data=data.replace(/(^|[^A-Za-z])(Frigid Mandragor Husk)(?=[^A-Za-z]|$)/gi, '$1呆板曼陀罗外壳');
data=data.replace(/(^|[^A-Za-z])(Champion's Dawn)(?=[^A-Za-z]|$)/gi, '$1勇士曙光');
data=data.replace(/(^|[^A-Za-z])(Cliffs of Dohjok)(?=[^A-Za-z]|$)/gi, '$1杜夏悬崖');
data=data.replace(/(^|[^A-Za-z])(Corsair)(?=[^A-Za-z]|$)/gi, '$1海盗');
data=data.replace(/(^|[^A-Za-z])(Copper Shilling)(?=[^A-Za-z]|$)/gi, '$1铜先令');
data=data.replace(/(^|[^A-Za-z])(The Wilds)(?=[^A-Za-z]|$)/gi, '$1荒原');
data=data.replace(/(^|[^A-Za-z])(Sage Lands)(?=[^A-Za-z]|$)/gi, '$1贤者领地');
data=data.replace(/(^|[^A-Za-z])(Wind Rider (Maguuma Jungle))(?=[^A-Za-z]|$)/gi, '$1驭风者');
data=data.replace(/(^|[^A-Za-z])(Ancient Eye)(?=[^A-Za-z]|$)/gi, '$1远古之眼');
data=data.replace(/(^|[^A-Za-z])(Sunspear Sanctuary)(?=[^A-Za-z]|$)/gi, '$1日戟避难所');
data=data.replace(/(^|[^A-Za-z])(Sunward Marches)(?=[^A-Za-z]|$)/gi, '$1向阳边境');
data=data.replace(/(^|[^A-Za-z])(Mirage Iboga)(?=[^A-Za-z]|$)/gi, '$1幻象伊波枷');
data=data.replace(/(^|[^A-Za-z])(Murmuring Thornbrush)(?=[^A-Za-z]|$)/gi, '$1荆棘之藤');
data=data.replace(/(^|[^A-Za-z])(Sentient Spore)(?=[^A-Za-z]|$)/gi, '$1知觉孢子');
data=data.replace(/(^|[^A-Za-z])(Gates of Kryta)(?=[^A-Za-z]|$)/gi, '$1科瑞塔关所');
data=data.replace(/(^|[^A-Za-z])(Scoundrel's Rise)(?=[^A-Za-z]|$)/gi, '$1恶汉山丘');
data=data.replace(/(^|[^A-Za-z])(Bog Skale)(?=[^A-Za-z]|$)/gi, '$1泥鳞怪');
data=data.replace(/(^|[^A-Za-z])(Bog Skale Fin)(?=[^A-Za-z]|$)/gi, '$1泥鳞怪的鳍');
data=data.replace(/(^|[^A-Za-z])(Zos Shivros Channel)(?=[^A-Za-z]|$)/gi, '$1佐席洛斯水道');
data=data.replace(/(^|[^A-Za-z])(Boreas Seabed)(?=[^A-Za-z]|$)/gi, '$1风神海床探索区');
data=data.replace(/(^|[^A-Za-z])(Kraken Spawn)(?=[^A-Za-z]|$)/gi, '$1海妖卵');
data=data.replace(/(^|[^A-Za-z])(Kraken Eye)(?=[^A-Za-z]|$)/gi, '$1海妖之眼');
data=data.replace(/(^|[^A-Za-z])(Grendich Courthouse)(?=[^A-Za-z]|$)/gi, '$1葛兰迪法院');
data=data.replace(/(^|[^A-Za-z])(Flame Temple Corridor)(?=[^A-Za-z]|$)/gi, '$1夏尔火焰神殿');
data=data.replace(/(^|[^A-Za-z])(Dragon's Gullet)(?=[^A-Za-z]|$)/gi, '$1巨龙峡谷');
data=data.replace(/(^|[^A-Za-z])(Abomination (NPC))(?=[^A-Za-z]|$)/gi, '$1憎恨者');
data=data.replace(/(^|[^A-Za-z])(Gruesome Ribcage)(?=[^A-Za-z]|$)/gi, '$1可怕的胸腔');
data=data.replace(/(^|[^A-Za-z])(Longeye's Ledge)(?=[^A-Za-z]|$)/gi, '$1长眼岩脉');
data=data.replace(/(^|[^A-Za-z])(Grothmar Wardowns)(?=[^A-Za-z]|$)/gi, '$1古斯玛战争丘陵地');
data=data.replace(/(^|[^A-Za-z])(Mandragor Dust Devil)(?=[^A-Za-z]|$)/gi, '$1曼陀罗尘魔');
data=data.replace(/(^|[^A-Za-z])(Mandragor Smoke Devil)(?=[^A-Za-z]|$)/gi, '$1曼陀罗烟魔');
data=data.replace(/(^|[^A-Za-z])(Vile Mandragor)(?=[^A-Za-z]|$)/gi, '$1暗黑曼陀罗');
data=data.replace(/(^|[^A-Za-z])(Fibrous Mandragor Root)(?=[^A-Za-z]|$)/gi, '$1纤维曼陀罗根');
data=data.replace(/(^|[^A-Za-z])(Chantry of Secrets)(?=[^A-Za-z]|$)/gi, '$1隐密教堂');
data=data.replace(/(^|[^A-Za-z])(Yatendi Canyons)(?=[^A-Za-z]|$)/gi, '$1亚天帝峡谷');
data=data.replace(/(^|[^A-Za-z])(Rain Beetle)(?=[^A-Za-z]|$)/gi, '$1雨甲虫');
data=data.replace(/(^|[^A-Za-z])(Rock Beetle)(?=[^A-Za-z]|$)/gi, '$1石甲虫');
data=data.replace(/(^|[^A-Za-z])(Geode)(?=[^A-Za-z]|$)/gi, '$1晶石');
data=data.replace(/(^|[^A-Za-z])(Vizunah Square (Local Quarter))(?=[^A-Za-z]|$)/gi, '$1薇茹广场本地');
data=data.replace(/(^|[^A-Za-z])(The Undercity)(?=[^A-Za-z]|$)/gi, '$1地下城');
data=data.replace(/(^|[^A-Za-z])(Kappa (level 20))(?=[^A-Za-z]|$)/gi, '$1河童');
data=data.replace(/(^|[^A-Za-z])(Ancient Kappa Shell)(?=[^A-Za-z]|$)/gi, '$1古河童壳');
data=data.replace(/(^|[^A-Za-z])(Temple of the Ages)(?=[^A-Za-z]|$)/gi, '$1世纪神殿');
data=data.replace(/(^|[^A-Za-z])(The Black Curtain)(?=[^A-Za-z]|$)/gi, '$1黑色帷幕');
data=data.replace(/(^|[^A-Za-z])(Fog Nightmare)(?=[^A-Za-z]|$)/gi, '$1迷雾梦靥');
data=data.replace(/(^|[^A-Za-z])(Shadowy Remnants)(?=[^A-Za-z]|$)/gi, '$1阴影残留物');
data=data.replace(/(^|[^A-Za-z])(Remains of Sahlahja)(?=[^A-Za-z]|$)/gi, '$1萨拉迦遗址');
data=data.replace(/(^|[^A-Za-z])(The Sulfurous Wastes)(?=[^A-Za-z]|$)/gi, '$1硫磺荒地');
data=data.replace(/(^|[^A-Za-z])(Awakened Cavalier)(?=[^A-Za-z]|$)/gi, '$1觉醒的骑士');
data=data.replace(/(^|[^A-Za-z])(Mummy Wrapping)(?=[^A-Za-z]|$)/gi, '$1木乃伊裹尸布');
data=data.replace(/(^|[^A-Za-z])(Tsumei Village)(?=[^A-Za-z]|$)/gi, '$1苏梅村');
data=data.replace(/(^|[^A-Za-z])(Sunqua Vale)(?=[^A-Za-z]|$)/gi, '$1桑泉谷');
data=data.replace(/(^|[^A-Za-z])(Sensali)(?=[^A-Za-z]|$)/gi, '$1圣沙利天狗');
data=data.replace(/(^|[^A-Za-z])(Feathered Scalp)(?=[^A-Za-z]|$)/gi, '$1羽头皮');
data=data.replace(/(^|[^A-Za-z])(Bone Palace)(?=[^A-Za-z]|$)/gi, '$1白骨宫殿');
data=data.replace(/(^|[^A-Za-z])(Joko's Domain)(?=[^A-Za-z]|$)/gi, '$1杰格领地');
data=data.replace(/(^|[^A-Za-z])(Gate of Torment)(?=[^A-Za-z]|$)/gi, '$1苦痛之门');
data=data.replace(/(^|[^A-Za-z])(Nightfallen Jahai)(?=[^A-Za-z]|$)/gi, '$1夜蚀暗殒 夏亥');
data=data.replace(/(^|[^A-Za-z])(Graven Monolith)(?=[^A-Za-z]|$)/gi, '$1铭刻石雕');
data=data.replace(/(^|[^A-Za-z])(Inscribed Shard)(?=[^A-Za-z]|$)/gi, '$1铭刻碎片');
data=data.replace(/(^|[^A-Za-z])(Vlox's Falls)(?=[^A-Za-z]|$)/gi, '$1弗洛克斯瀑布');
data=data.replace(/(^|[^A-Za-z])(Arbor Bay)(?=[^A-Za-z]|$)/gi, '$1亚伯湾');
data=data.replace(/(^|[^A-Za-z])(Krait)(?=[^A-Za-z]|$)/gi, '$1环蛇');
data=data.replace(/(^|[^A-Za-z])(Krait Skin)(?=[^A-Za-z]|$)/gi, '$1环蛇皮');
data=data.replace(/(^|[^A-Za-z])(The Granite Citadel)(?=[^A-Za-z]|$)/gi, '$1花岗岩堡垒');
data=data.replace(/(^|[^A-Za-z])(Tasca's Demise)(?=[^A-Za-z]|$)/gi, '$1塔斯加之死');
data=data.replace(/(^|[^A-Za-z])(Stone Summit)(?=[^A-Za-z]|$)/gi, '$1石峰矮人');
data=data.replace(/(^|[^A-Za-z])(Stone Summit Badge)(?=[^A-Za-z]|$)/gi, '$1石峰标志');
data=data.replace(/(^|[^A-Za-z])(Defend Droknar's Forge)(?=[^A-Za-z]|$)/gi, '$1保卫卓克纳熔炉');
data=data.replace(/(^|[^A-Za-z])(Lutgardis Conservatory)(?=[^A-Za-z]|$)/gi, '$1路嘉蒂斯温室');
data=data.replace(/(^|[^A-Za-z])(Melandru's Hope)(?=[^A-Za-z]|$)/gi, '$1梅兰朵的盼望');
data=data.replace(/(^|[^A-Za-z])(Echovald Forest)(?=[^A-Za-z]|$)/gi, '$1石化森林');
data=data.replace(/(^|[^A-Za-z])(Dredge)(?=[^A-Za-z]|$)/gi, '$1挖掘者');
data=data.replace(/(^|[^A-Za-z])(Dredge Incisor)(?=[^A-Za-z]|$)/gi, '$1挖掘者之牙');
data=data.replace(/(^|[^A-Za-z])(Grendich Courthouse)(?=[^A-Za-z]|$)/gi, '$1葛兰迪法院');
data=data.replace(/(^|[^A-Za-z])(Diessa Lowlands)(?=[^A-Za-z]|$)/gi, '$1底耶沙低地');
data=data.replace(/(^|[^A-Za-z])(Gargoyle)(?=[^A-Za-z]|$)/gi, '$1石像鬼');
data=data.replace(/(^|[^A-Za-z])(Flash Gargoyle)(?=[^A-Za-z]|$)/gi, '$1迅速石像鬼');
data=data.replace(/(^|[^A-Za-z])(Shatter Gargoyle)(?=[^A-Za-z]|$)/gi, '$1破碎石像鬼');
data=data.replace(/(^|[^A-Za-z])(Resurrect Gargoyle)(?=[^A-Za-z]|$)/gi, '$1复活石像鬼');
data=data.replace(/(^|[^A-Za-z])(Singed Gargoyle Skull)(?=[^A-Za-z]|$)/gi, '$1烧焦的石像鬼头颅');
data=data.replace(/(^|[^A-Za-z])(Pogahn Passage)(?=[^A-Za-z]|$)/gi, '$1波甘驿站');
data=data.replace(/(^|[^A-Za-z])(Gandara, the Moon Fortress)(?=[^A-Za-z]|$)/gi, '$1弦月要塞 干达拉');
data=data.replace(/(^|[^A-Za-z])(Kournan military)(?=[^A-Za-z]|$)/gi, '$1高楠士兵');
data=data.replace(/(^|[^A-Za-z])(Kournan Pendant)(?=[^A-Za-z]|$)/gi, '$1高楠垂饰');
data=data.replace(/(^|[^A-Za-z])(Sunjiang District)(?=[^A-Za-z]|$)/gi, '$1孙江行政区');
data=data.replace(/(^|[^A-Za-z])(Shenzun Tunnels)(?=[^A-Za-z]|$)/gi, '$1申赞通道');
data=data.replace(/(^|[^A-Za-z])(Plant Fiber)(?=[^A-Za-z]|$)/gi, '$1植物纤维');
data=data.replace(/(^|[^A-Za-z])(Tempered Glass Vial)(?=[^A-Za-z]|$)/gi, '$1调合后的玻璃瓶');
data=data.replace(/(^|[^A-Za-z])(Kaineng Center)(?=[^A-Za-z]|$)/gi, '$1凯宁中心');
data=data.replace(/(^|[^A-Za-z])(Vial of Ink)(?=[^A-Za-z]|$)/gi, '$1小瓶油水');
data=data.replace(/(^|[^A-Za-z])(Camp Rankor)(?=[^A-Za-z]|$)/gi, '$1蓝口营地');
data=data.replace(/(^|[^A-Za-z])(Talus Chute)(?=[^A-Za-z]|$)/gi, '$1碎石坡道');
data=data.replace(/(^|[^A-Za-z])(Mountain Troll)(?=[^A-Za-z]|$)/gi, '$1山巨魔');
data=data.replace(/(^|[^A-Za-z])(Mountain Troll Tusk)(?=[^A-Za-z]|$)/gi, '$1山巨魔獠牙');
data=data.replace(/(^|[^A-Za-z])(Kodonur Crossroads)(?=[^A-Za-z]|$)/gi, '$1科登诺路口');
data=data.replace(/(^|[^A-Za-z])(Dejarin Estate)(?=[^A-Za-z]|$)/gi, '$1达贾林庄');
data=data.replace(/(^|[^A-Za-z])(Blue Tongue Heket)(?=[^A-Za-z]|$)/gi, '$1蓝舌哈克蛙');
data=data.replace(/(^|[^A-Za-z])(Beast Sworn Heket)(?=[^A-Za-z]|$)/gi, '$1野性哈克蛙');
data=data.replace(/(^|[^A-Za-z])(Blood Cowl Heket)(?=[^A-Za-z]|$)/gi, '$1冷血哈克蛙');
data=data.replace(/(^|[^A-Za-z])(Heket Tongue)(?=[^A-Za-z]|$)/gi, '$1哈克蛙舌');
data=data.replace(/(^|[^A-Za-z])(Longeye's Ledge)(?=[^A-Za-z]|$)/gi, '$1长眼岩脉');
data=data.replace(/(^|[^A-Za-z])(Bjora Marches)(?=[^A-Za-z]|$)/gi, '$1碧拉边境');
data=data.replace(/(^|[^A-Za-z])(Jotun Skullsmasher)(?=[^A-Za-z]|$)/gi, '$1碎骨角顿');
data=data.replace(/(^|[^A-Za-z])(Jotun Mindbreaker)(?=[^A-Za-z]|$)/gi, '$1断绪角顿');
data=data.replace(/(^|[^A-Za-z])(Jotun Bladeturner)(?=[^A-Za-z]|$)/gi, '$1转刃角顿');
data=data.replace(/(^|[^A-Za-z])(Jotun Pelt)(?=[^A-Za-z]|$)/gi, '$1角顿皮毛');
data=data.replace(/(^|[^A-Za-z])(Harvest Temple)(?=[^A-Za-z]|$)/gi, '$1丰收神殿');
data=data.replace(/(^|[^A-Za-z])(Unwaking Waters)(?=[^A-Za-z]|$)/gi, '$1沉睡之水');
data=data.replace(/(^|[^A-Za-z])(Saltspray Dragon)(?=[^A-Za-z]|$)/gi, '$1盐雾之龙');
data=data.replace(/(^|[^A-Za-z])(Rockhide Dragon)(?=[^A-Za-z]|$)/gi, '$1岩皮之龙');
data=data.replace(/(^|[^A-Za-z])(Azure Crest)(?=[^A-Za-z]|$)/gi, '$1湛蓝羽冠');
data=data.replace(/(^|[^A-Za-z])(Yak's Bend)(?=[^A-Za-z]|$)/gi, '$1牦牛村');
data=data.replace(/(^|[^A-Za-z])(Ascalon Foothi​​lls)(?=[^A-Za-z]|$)/gi, '$1阿斯卡隆丘陵');
data=data.replace(/(^|[^A-Za-z])(Hydra)(?=[^A-Za-z]|$)/gi, '$1三头龙');
data=data.replace(/(^|[^A-Za-z])(Leathery Claw)(?=[^A-Za-z]|$)/gi, '$1强韧的爪');
data=data.replace(/(^|[^A-Za-z])(Grand Court of Sebelkeh)(?=[^A-Za-z]|$)/gi, '$1希贝克大宫廷');
data=data.replace(/(^|[^A-Za-z])(The Mirror of Lyss)(?=[^A-Za-z]|$)/gi, '$1丽之镜湖');
data=data.replace(/(^|[^A-Za-z])(Roaring Ether)(?=[^A-Za-z]|$)/gi, '$1苍穹咆啸者');
data=data.replace(/(^|[^A-Za-z])(Roaring Ether Heart)(?=[^A-Za-z]|$)/gi, '$1苍穹咆啸者之心');
data=data.replace(/(^|[^A-Za-z])(Senji's Corner)(?=[^A-Za-z]|$)/gi, '$1山吉之街');
data=data.replace(/(^|[^A-Za-z])(Xaquang Skyway)(?=[^A-Za-z]|$)/gi, '$1夏安便道');
data=data.replace(/(^|[^A-Za-z])(Vermin)(?=[^A-Za-z]|$)/gi, '$1寄生虫');
data=data.replace(/(^|[^A-Za-z])(Vermin Hides)(?=[^A-Za-z]|$)/gi, '$1寄生虫皮革');
data=data.replace(/(^|[^A-Za-z])(Sunspear Great Hall)(?=[^A-Za-z]|$)/gi, '$1日戟大会堂');
data=data.replace(/(^|[^A-Za-z])(Plains of Jarin)(?=[^A-Za-z]|$)/gi, '$1贾林平原');
data=data.replace(/(^|[^A-Za-z])(Fanged Iboga)(?=[^A-Za-z]|$)/gi, '$1尖牙伊波茄');
data=data.replace(/(^|[^A-Za-z])(Iboga Petal)(?=[^A-Za-z]|$)/gi, '$1伊波茄花瓣');
data=data.replace(/(^|[^A-Za-z])(Champion's Dawn)(?=[^A-Za-z]|$)/gi, '$1勇士曙光');
data=data.replace(/(^|[^A-Za-z])(Chef Volon)(?=[^A-Za-z]|$)/gi, '$1大厨 瓦隆');
data=data.replace(/(^|[^A-Za-z])(Pahnai Salad)(?=[^A-Za-z]|$)/gi, '$1伊波茄沙拉');
data=data.replace(/(^|[^A-Za-z])(Seitung Harbor)(?=[^A-Za-z]|$)/gi, '$1青函港');
data=data.replace(/(^|[^A-Za-z])(Jaya Bluffs)(?=[^A-Za-z]|$)/gi, '$1蛇野断崖');
data=data.replace(/(^|[^A-Za-z])(Mountain Yeti)(?=[^A-Za-z]|$)/gi, '$1山雪怪');
data=data.replace(/(^|[^A-Za-z])(Longhair Yeti)(?=[^A-Za-z]|$)/gi, '$1长毛雪怪');
data=data.replace(/(^|[^A-Za-z])(Red Yeti)(?=[^A-Za-z]|$)/gi, '$1红雪怪');
data=data.replace(/(^|[^A-Za-z])(Stolen Supplies)(?=[^A-Za-z]|$)/gi, '$1失窃的补给品');
data=data.replace(/(^|[^A-Za-z])(Aurora Glade)(?=[^A-Za-z]|$)/gi, '$1欧若拉林地');
data=data.replace(/(^|[^A-Za-z])(Ettin's Back)(?=[^A-Za-z]|$)/gi, '$1双头怪隐匿地');
data=data.replace(/(^|[^A-Za-z])(Dry Top)(?=[^A-Za-z]|$)/gi, '$1干燥高地');
data=data.replace(/(^|[^A-Za-z])(Nicholas the Traveler)(?=[^A-Za-z]|$)/gi, '$1地图');
data=data.replace(/(^|[^A-Za-z])(Thorn Stalker)(?=[^A-Za-z]|$)/gi, '$1棘刺潜行者');
data=data.replace(/(^|[^A-Za-z])(Tangled Seed)(?=[^A-Za-z]|$)/gi, '$1纠结的种子');
data=data.replace(/(^|[^A-Za-z])(Iron Mines of Moladune)(?=[^A-Za-z]|$)/gi, '$1莫拉登矿山');
data=data.replace(/(^|[^A-Za-z])(Frozen Forest)(?=[^A-Za-z]|$)/gi, '$1冰冻森林');
data=data.replace(/(^|[^A-Za-z])(Pinesoul)(?=[^A-Za-z]|$)/gi, '$1松木怪');
data=data.replace(/(^|[^A-Za-z])(Alpine Seed)(?=[^A-Za-z]|$)/gi, '$1柏木种子');
data=data.replace(/(^|[^A-Za-z])(Gadd's Encampment)(?=[^A-Za-z]|$)/gi, '$1盖德营区');
data=data.replace(/(^|[^A-Za-z])(Sparkfly Swamp)(?=[^A-Za-z]|$)/gi, '$1火星蝇沼泽');
data=data.replace(/(^|[^A-Za-z])(Bogroot Growths)(?=[^A-Za-z]|$)/gi, '$1泥塘根源地');
data=data.replace(/(^|[^A-Za-z])(Heket)(?=[^A-Za-z]|$)/gi, '$1青蛙族群');
data=data.replace(/(^|[^A-Za-z])(Rata Sum)(?=[^A-Za-z]|$)/gi, '$1洛达顶点');
data=data.replace(/(^|[^A-Za-z])(Magus Stones)(?=[^A-Za-z]|$)/gi, '$1马古斯之石');
data=data.replace(/(^|[^A-Za-z])(Oola's Lab)(?=[^A-Za-z]|$)/gi, '$1呜拉实验室');
data=data.replace(/(^|[^A-Za-z])(Hylek Amini)(?=[^A-Za-z]|$)/gi, '$1海格克 阿纳尼');
data=data.replace(/(^|[^A-Za-z])(Hylek Nahualli)(?=[^A-Za-z]|$)/gi, '$1海格克 纳猾里');
data=data.replace(/(^|[^A-Za-z])(Hylek Tlamatini)(?=[^A-Za-z]|$)/gi, '$1海格克 拉玛提尼');
data=data.replace(/(^|[^A-Za-z])(Amphibian Tongue)(?=[^A-Za-z]|$)/gi, '$1双面人的舌头');
data=data.replace(/(^|[^A-Za-z])(Kodonur Crossroads)(?=[^A-Za-z]|$)/gi, '$1科登诺路口');
data=data.replace(/(^|[^A-Za-z])(The Floodplain of Mahnkelon)(?=[^A-Za-z]|$)/gi, '$1曼克隆泛滥平原');
data=data.replace(/(^|[^A-Za-z])(Embark Beach)(?=[^A-Za-z]|$)/gi, '$1征途海滩');
data=data.replace(/(^|[^A-Za-z])(Merchant)(?=[^A-Za-z]|$)/gi, '$1杂货商人');
data=data.replace(/(^|[^A-Za-z])(Dwarven Ale)(?=[^A-Za-z]|$)/gi, '$1矮人啤酒');
data=data.replace(/(^|[^A-Za-z])(Gunnar's Hold)(?=[^A-Za-z]|$)/gi, '$1甘拿的占领地');
data=data.replace(/(^|[^A-Za-z])(Kilroy Stonekin)(?=[^A-Za-z]|$)/gi, '$1基罗伊石族');
data=data.replace(/(^|[^A-Za-z])(Fronis Irontoe's Lair)(?=[^A-Za-z]|$)/gi, '$1铁趾 佛朗尼的巢穴');
data=data.replace(/(^|[^A-Za-z])(Irontoe's Chest)(?=[^A-Za-z]|$)/gi, '$1最终宝箱');
data=data.replace(/(^|[^A-Za-z])(Eredon Terrace)(?=[^A-Za-z]|$)/gi, '$1雷尔登平地');
data=data.replace(/(^|[^A-Za-z])(Maishang Hills)(?=[^A-Za-z]|$)/gi, '$1麦尚山丘');
data=data.replace(/(^|[^A-Za-z])(Boreas Seabed)(?=[^A-Za-z]|$)/gi, '$1风神海床');
data=data.replace(/(^|[^A-Za-z])(Pongmei Valley)(?=[^A-Za-z]|$)/gi, '$1朋美谷');
data=data.replace(/(^|[^A-Za-z])(Island Guardian)(?=[^A-Za-z]|$)/gi, '$1岛屿守护者');
data=data.replace(/(^|[^A-Za-z])(Guardian Moss)(?=[^A-Za-z]|$)/gi, '$1守护者苔');
data=data.replace(/(^|[^A-Za-z])(Gate of Desolation)(?=[^A-Za-z]|$)/gi, '$1荒芜之地入口');
data=data.replace(/(^|[^A-Za-z])(Turai's Procession)(?=[^A-Za-z]|$)/gi, '$1托雷长廊');
data=data.replace(/(^|[^A-Za-z])(Water Djinn)(?=[^A-Za-z]|$)/gi, '$1水巨灵');
data=data.replace(/(^|[^A-Za-z])(Water Djinn Essence)(?=[^A-Za-z]|$)/gi, '$1水巨灵精华');
data=data.replace(/(^|[^A-Za-z])(Old Ascalon)(?=[^A-Za-z]|$)/gi, '$1旧阿斯卡隆');
data=data.replace(/(^|[^A-Za-z])(Hulking Stone Elemental)(?=[^A-Za-z]|$)/gi, '$1巨石元素');
data=data.replace(/(^|[^A-Za-z])(Scorched Lodestone)(?=[^A-Za-z]|$)/gi, '$1烧焦的磁石');
data=data.replace(/(^|[^A-Za-z])(Amatz Basin)(?=[^A-Za-z]|$)/gi, '$1亚马兹盆地');
data=data.replace(/(^|[^A-Za-z])(Mourning Veil Falls)(?=[^A-Za-z]|$)/gi, '$1哀伤之幕瀑布');
data=data.replace(/(^|[^A-Za-z])(Rare material trader)(?=[^A-Za-z]|$)/gi, '$1稀有材料商');
data=data.replace(/(^|[^A-Za-z])(Tempered Glass Vial)(?=[^A-Za-z]|$)/gi, '$1调和后的玻璃瓶');
data=data.replace(/(^|[^A-Za-z])(Bergen Hot Springs)(?=[^A-Za-z]|$)/gi, '$1卑尔根温泉');
data=data.replace(/(^|[^A-Za-z])(Nebo Terrace)(?=[^A-Za-z]|$)/gi, '$1尼伯山丘');
data=data.replace(/(^|[^A-Za-z])(Cursed Lands)(?=[^A-Za-z]|$)/gi, '$1诅咒之地');
data=data.replace(/(^|[^A-Za-z])(Skeleton Ranger)(?=[^A-Za-z]|$)/gi, '$1骷髅游侠');
data=data.replace(/(^|[^A-Za-z])(Skeleton Sorcerer)(?=[^A-Za-z]|$)/gi, '$1骷髅巫师');
data=data.replace(/(^|[^A-Za-z])(Grasping Ghoul)(?=[^A-Za-z]|$)/gi, '$1贪婪的食尸鬼');
data=data.replace(/(^|[^A-Za-z])(Zombie Warlock)(?=[^A-Za-z]|$)/gi, '$1僵尸法魔');
data=data.replace(/(^|[^A-Za-z])(Skeleton Bowmaster)(?=[^A-Za-z]|$)/gi, '$1骷髅弓箭手');
data=data.replace(/(^|[^A-Za-z])(Decayed Orr Emblem)(?=[^A-Za-z]|$)/gi, '$1腐烂的欧尔纹章');
data=data.replace(/(^|[^A-Za-z])(Beetletun)(?=[^A-Za-z]|$)/gi, '$1甲虫镇');
data=data.replace(/(^|[^A-Za-z])(Watchtower Coast)(?=[^A-Za-z]|$)/gi, '$1瞭望塔海岸');
data=data.replace(/(^|[^A-Za-z])(Gates of Kryta)(?=[^A-Za-z]|$)/gi, '$1科瑞塔关所');
data=data.replace(/(^|[^A-Za-z])(Scoundrel's Rise)(?=[^A-Za-z]|$)/gi, '$1恶汉山丘');
data=data.replace(/(^|[^A-Za-z])(Mergoyle Wavebreaker)(?=[^A-Za-z]|$)/gi, '$1碎浪石像魔');
data=data.replace(/(^|[^A-Za-z])(Mergoyle Skull)(?=[^A-Za-z]|$)/gi, '$1石像魔头颅');
data=data.replace(/(^|[^A-Za-z])(Nundu Bay)(?=[^A-Za-z]|$)/gi, '$1纳度湾');
data=data.replace(/(^|[^A-Za-z])(Marga Coast)(?=[^A-Za-z]|$)/gi, '$1马加海岸');
data=data.replace(/(^|[^A-Za-z])(Yohlon Haven)(?=[^A-Za-z]|$)/gi, '$1犹朗避难所');
data=data.replace(/(^|[^A-Za-z])(Arkjok Ward)(?=[^A-Za-z]|$)/gi, '$1阿尔科监禁区');
data=data.replace(/(^|[^A-Za-z])(Bladed Veldt Termite)(?=[^A-Za-z]|$)/gi, '$1利刃草原蚁');
data=data.replace(/(^|[^A-Za-z])(Veldt Beetle Lance)(?=[^A-Za-z]|$)/gi, '$1草原尖刺甲虫');
data=data.replace(/(^|[^A-Za-z])(Veldt Beetle Queen)(?=[^A-Za-z]|$)/gi, '$1草原甲虫后');
data=data.replace(/(^|[^A-Za-z])(Insect Carapace)(?=[^A-Za-z]|$)/gi, '$1甲虫壳');
data=data.replace(/(^|[^A-Za-z])(Cavalon)(?=[^A-Za-z]|$)/gi, '$1卡瓦隆');
data=data.replace(/(^|[^A-Za-z])(Archipelagos)(?=[^A-Za-z]|$)/gi, '$1群岛');
data=data.replace(/(^|[^A-Za-z])(Creeping Carp)(?=[^A-Za-z]|$)/gi, '$1爬行鲤鱼');
data=data.replace(/(^|[^A-Za-z])(Scuttle Fish)(?=[^A-Za-z]|$)/gi, '$1甲板鱼');
data=data.replace(/(^|[^A-Za-z])(Irukandji)(?=[^A-Za-z]|$)/gi, '$1毒水母');
data=data.replace(/(^|[^A-Za-z])(Black Pearl)(?=[^A-Za-z]|$)/gi, '$1黑珍珠');
data=data.replace(/(^|[^A-Za-z])(Bone Palace)(?=[^A-Za-z]|$)/gi, '$1白骨宫殿');
data=data.replace(/(^|[^A-Za-z])(Joko's Domain)(?=[^A-Za-z]|$)/gi, '$1杰格领地');
data=data.replace(/(^|[^A-Za-z])(The Shattered Ravines)(?=[^A-Za-z]|$)/gi, '$1碎裂沟谷');
data=data.replace(/(^|[^A-Za-z])(Basalt Grotto)(?=[^A-Za-z]|$)/gi, '$1玄武岩石穴');
data=data.replace(/(^|[^A-Za-z])(Sandstorm Crag)(?=[^A-Za-z]|$)/gi, '$1沙风暴．克雷格');
data=data.replace(/(^|[^A-Za-z])(Shambling Mesa)(?=[^A-Za-z]|$)/gi, '$1震颤者．梅萨');
data=data.replace(/(^|[^A-Za-z])(Icy Hump)(?=[^A-Za-z]|$)/gi, '$1喷沙磁石');
data=data.replace(/(^|[^A-Za-z])(Yak's Bend)(?=[^A-Za-z]|$)/gi, '$1牦牛村');
data=data.replace(/(^|[^A-Za-z])(Traveler's Vale)(?=[^A-Za-z]|$)/gi, '$1旅人谷');
data=data.replace(/(^|[^A-Za-z])(Iron Horse Mine)(?=[^A-Za-z]|$)/gi, '$1铁马矿山');
data=data.replace(/(^|[^A-Za-z])(Beacon's Perch)(?=[^A-Za-z]|$)/gi, '$1毕肯高地');
data=data.replace(/(^|[^A-Za-z])(Deldrimor Bowl)(?=[^A-Za-z]|$)/gi, '$1戴尔迪摩盆地');
data=data.replace(/(^|[^A-Za-z])(Griffon's Mouth)(?=[^A-Za-z]|$)/gi, '$1狮鹫兽隘口');
data=data.replace(/(^|[^A-Za-z])(Snow Ettin)(?=[^A-Za-z]|$)/gi, '$1冰雪双头巨人');
data=data.replace(/(^|[^A-Za-z])(Icy Hump)(?=[^A-Za-z]|$)/gi, '$1冰雪瘤');
data=data.replace(/(^|[^A-Za-z])(Ran Musu Gardens)(?=[^A-Za-z]|$)/gi, '$1岚穆苏花园');
data=data.replace(/(^|[^A-Za-z])(Minister Cho's Estate)(?=[^A-Za-z]|$)/gi, '$1周大臣庄园');
data=data.replace(/(^|[^A-Za-z])(Sickened Servant)(?=[^A-Za-z]|$)/gi, '$1病变的使者');
data=data.replace(/(^|[^A-Za-z])(Sickened Peasant)(?=[^A-Za-z]|$)/gi, '$1病变的书记');
data=data.replace(/(^|[^A-Za-z])(Sickened Guard (warrior))(?=[^A-Za-z]|$)/gi, '$1病变的警卫');
data=data.replace(/(^|[^A-Za-z])(Forgotten Trinket Box)(?=[^A-Za-z]|$)/gi, '$1被遗忘的小箱子');
data=data.replace(/(^|[^A-Za-z])(Ventari's Refuge)(?=[^A-Za-z]|$)/gi, '$1凡特里庇护所');
data=data.replace(/(^|[^A-Za-z])(Ettin's Back)(?=[^A-Za-z]|$)/gi, '$1双头怪隐匿第');
data=data.replace(/(^|[^A-Za-z])(Reed Bog)(?=[^A-Za-z]|$)/gi, '$1芦苇沼泽地');
data=data.replace(/(^|[^A-Za-z])(The Falls)(?=[^A-Za-z]|$)/gi, '$1陷落区');
data=data.replace(/(^|[^A-Za-z])(Maguuma Spider)(?=[^A-Za-z]|$)/gi, '$1梅古玛蜘蛛');
data=data.replace(/(^|[^A-Za-z])(Maguuma Spider Web)(?=[^A-Za-z]|$)/gi, '$1梅古玛蜘蛛丝');
data=data.replace(/(^|[^A-Za-z])(Jennur's Horde)(?=[^A-Za-z]|$)/gi, '$1征纳群落');
data=data.replace(/(^|[^A-Za-z])(Vehjin Mines)(?=[^A-Za-z]|$)/gi, '$1威金矿坑');
data=data.replace(/(^|[^A-Za-z])(Cobalt Scabara)(?=[^A-Za-z]|$)/gi, '$1深蓝斯卡巴拉');
data=data.replace(/(^|[^A-Za-z])(Cobalt Mokele)(?=[^A-Za-z]|$)/gi, '$1深蓝魔克雷');
data=data.replace(/(^|[^A-Za-z])(Cobalt Shrieker)(?=[^A-Za-z]|$)/gi, '$1深蓝尖啸者');
data=data.replace(/(^|[^A-Za-z])(Cobalt Talon)(?=[^A-Za-z]|$)/gi, '$1深蓝之爪');
data=data.replace(/(^|[^A-Za-z])(Sunspear Sanctuary)(?=[^A-Za-z]|$)/gi, '$1日戟避难所');
data=data.replace(/(^|[^A-Za-z])(Command Post)(?=[^A-Za-z]|$)/gi, '$1指挥所');
data=data.replace(/(^|[^A-Za-z])(Jahai Bluffs)(?=[^A-Za-z]|$)/gi, '$1夏亥峭壁');
data=data.replace(/(^|[^A-Za-z])(Rare material trader)(?=[^A-Za-z]|$)/gi, '$1稀有材料商人');
data=data.replace(/(^|[^A-Za-z])(Elonian Leather Square)(?=[^A-Za-z]|$)/gi, '$1伊洛那皮革');
data=data.replace(/(^|[^A-Za-z])(Deldrimor War Camp)(?=[^A-Za-z]|$)/gi, '$1戴尔狄摩兵营');
data=data.replace(/(^|[^A-Za-z])(Grenth's Footprint)(?=[^A-Za-z]|$)/gi, '$1古兰斯的足迹');
data=data.replace(/(^|[^A-Za-z])(Sorrow's F​​urnace)(?=[^A-Za-z]|$)/gi, '$1哀伤熔炉');
data=data.replace(/(^|[^A-Za-z])(Priest of Sorrows)(?=[^A-Za-z]|$)/gi, '$1哀伤祭司');
data=data.replace(/(^|[^A-Za-z])(Summit Warden)(?=[^A-Za-z]|$)/gi, '$1石峰看守者');
data=data.replace(/(^|[^A-Za-z])(Summit Surveyor)(?=[^A-Za-z]|$)/gi, '$1石峰测量员');
data=data.replace(/(^|[^A-Za-z])(Summit Dark Binder)(?=[^A-Za-z]|$)/gi, '$1石峰黑暗束缚者');
data=data.replace(/(^|[^A-Za-z])(Summit Deep Knight)(?=[^A-Za-z]|$)/gi, '$1石峰深渊骑士');
data=data.replace(/(^|[^A-Za-z])(Summit Taskmaster)(?=[^A-Za-z]|$)/gi, '$1石峰工头');
data=data.replace(/(^|[^A-Za-z])(Enslavement Stone)(?=[^A-Za-z]|$)/gi, '$1奴隶石');
data=data.replace(/(^|[^A-Za-z])(Ventari's Refuge)(?=[^A-Za-z]|$)/gi, '$1凡特里避难所');
data=data.replace(/(^|[^A-Za-z])(Ettin's Back)(?=[^A-Za-z]|$)/gi, '$1双头怪隐匿地');
data=data.replace(/(^|[^A-Za-z])(The Wilds)(?=[^A-Za-z]|$)/gi, '$1荒原主线');
data=data.replace(/(^|[^A-Za-z])(Moss Scarab)(?=[^A-Za-z]|$)/gi, '$1苔圣甲虫');
data=data.replace(/(^|[^A-Za-z])(Mossy Mandible)(?=[^A-Za-z]|$)/gi, '$1生苔下颚骨');
data=data.replace(/(^|[^A-Za-z])(Ran Musu Gardens)(?=[^A-Za-z]|$)/gi, '$1岚穆苏花园');
data=data.replace(/(^|[^A-Za-z])(Kinya Province)(?=[^A-Za-z]|$)/gi, '$1欣弥领地');
data=data.replace(/(^|[^A-Za-z])(Panjiang Peninsula)(?=[^A-Za-z]|$)/gi, '$1班让半岛');
data=data.replace(/(^|[^A-Za-z])(Crimson Skull)(?=[^A-Za-z]|$)/gi, '$1红颅');
data=data.replace(/(^|[^A-Za-z])(Copper Crimson Skull Coin)(?=[^A-Za-z]|$)/gi, '$1红颅铜币');
data=data.replace(/(^|[^A-Za-z])(Dunes of Despair)(?=[^A-Za-z]|$)/gi, '$1绝望沙丘');
data=data.replace(/(^|[^A-Za-z])(Vulture Drifts)(?=[^A-Za-z]|$)/gi, '$1秃鹰沙丘');
data=data.replace(/(^|[^A-Za-z])(Enchanted Hammer)(?=[^A-Za-z]|$)/gi, '$1附魔巨锤兵');
data=data.replace(/(^|[^A-Za-z])(Enchanted Sword)(?=[^A-Za-z]|$)/gi, '$1附魔长剑兵');
data=data.replace(/(^|[^A-Za-z])(Enchanted Bow)(?=[^A-Za-z]|$)/gi, '$1附魔弓兵');
data=data.replace(/(^|[^A-Za-z])(Forgotten Seal)(?=[^A-Za-z]|$)/gi, '$1遗忘者图章');
data=data.replace(/(^|[^A-Za-z])(Dasha Vestibule)(?=[^A-Za-z]|$)/gi, '$1达沙走廊');
data=data.replace(/(^|[^A-Za-z])(The Hidden City of Ahdashim)(?=[^A-Za-z]|$)/gi, '$1隐藏之城 哈达辛');
data=data.replace(/(^|[^A-Za-z])(Key of Ahdashim)(?=[^A-Za-z]|$)/gi, '$1哈达辛之钥');
data=data.replace(/(^|[^A-Za-z])(Diamond Djinn)(?=[^A-Za-z]|$)/gi, '$1钻石巨灵');
data=data.replace(/(^|[^A-Za-z])(Diamond Djinn Essence)(?=[^A-Za-z]|$)/gi, '$1钻石巨灵精华');
data=data.replace(/(^|[^A-Za-z])(Temple of the Ages)(?=[^A-Za-z]|$)/gi, '$1世纪神殿');
data=data.replace(/(^|[^A-Za-z])(Talmark Wilderness)(?=[^A-Za-z]|$)/gi, '$1突马克荒地');
data=data.replace(/(^|[^A-Za-z])(Bergen Hot Springs)(?=[^A-Za-z]|$)/gi, '$1卑尔根温泉');
data=data.replace(/(^|[^A-Za-z])(Cursed Lands)(?=[^A-Za-z]|$)/gi, '$1诅咒之地探索区');
data=data.replace(/(^|[^A-Za-z])(Oakheart (Kryta))(?=[^A-Za-z]|$)/gi, '$1橡树妖');
data=data.replace(/(^|[^A-Za-z])(Ancient Oakheart)(?=[^A-Za-z]|$)/gi, '$1古老橡树妖');
data=data.replace(/(^|[^A-Za-z])(Spined Aloe)(?=[^A-Za-z]|$)/gi, '$1突刺芦荟');
data=data.replace(/(^|[^A-Za-z])(Reed Stalker)(?=[^A-Za-z]|$)/gi, '$1芦苇潜行者');
data=data.replace(/(^|[^A-Za-z])(Abnormal Seed)(?=[^A-Za-z]|$)/gi, '$1畸形的种子');
data=data.replace(/(^|[^A-Za-z])(The Mouth of Torment)(?=[^A-Za-z]|$)/gi, '$1苦痛之地隘口');
data=data.replace(/(^|[^A-Za-z])(The Ruptured Heart)(?=[^A-Za-z]|$)/gi, '$1破裂之心');
data=data.replace(/(^|[^A-Za-z])(Gate of Torment)(?=[^A-Za-z]|$)/gi, '$1苦痛之门');
data=data.replace(/(^|[^A-Za-z])(Realm of Torment)(?=[^A-Za-z]|$)/gi, '$1苦痛领域');
data=data.replace(/(^|[^A-Za-z])(Nightfallen Jahai)(?=[^A-Za-z]|$)/gi, '$1夜蚀暗殒 夏亥探索区');
data=data.replace(/(^|[^A-Za-z])(Arm of Insanity)(?=[^A-Za-z]|$)/gi, '$1狂乱武装');
data=data.replace(/(^|[^A-Za-z])(Scythe of Chaos)(?=[^A-Za-z]|$)/gi, '$1混沌镰刀');
data=data.replace(/(^|[^A-Za-z])(Blade of Corruption)(?=[^A-Za-z]|$)/gi, '$1堕落之刃');
data=data.replace(/(^|[^A-Za-z])(Shadow of Fear)(?=[^A-Za-z]|$)/gi, '$1恐惧暗影');
data=data.replace(/(^|[^A-Za-z])(Rain of Terror)(?=[^A-Za-z]|$)/gi, '$1惊骇之雨');
data=data.replace(/(^|[^A-Za-z])(Herald of Nightmares)(?=[^A-Za-z]|$)/gi, '$1梦靥使者');
data=data.replace(/(^|[^A-Za-z])(Spear of Torment)(?=[^A-Za-z]|$)/gi, '$1苦痛之矛');
data=data.replace(/(^|[^A-Za-z])(Word of Madness)(?=[^A-Za-z]|$)/gi, '$1疯狂话语');
data=data.replace(/(^|[^A-Za-z])(Demonic Relic)(?=[^A-Za-z]|$)/gi, '$1恶魔残片');
data=data.replace(/(^|[^A-Za-z])(Ice Tooth Cave)(?=[^A-Za-z]|$)/gi, '$1冰牙洞穴');
data=data.replace(/(^|[^A-Za-z])(Anvil Rock)(?=[^A-Za-z]|$)/gi, '$1铁砧石');
data=data.replace(/(^|[^A-Za-z])(Frostfire Dryder)(?=[^A-Za-z]|$)/gi, '$1霜火蛛化精灵');
data=data.replace(/(^|[^A-Za-z])(Frostfire Fang)(?=[^A-Za-z]|$)/gi, '$1霜火尖牙');
data=data.replace(/(^|[^A-Za-z])(Boreas Seabed)(?=[^A-Za-z]|$)/gi, '$1风神海床');
data=data.replace(/(^|[^A-Za-z])(Pongmei Valley)(?=[^A-Za-z]|$)/gi, '$1朋美谷');
data=data.replace(/(^|[^A-Za-z])(Rot Wallow)(?=[^A-Za-z]|$)/gi, '$1腐败兽');
data=data.replace(/(^|[^A-Za-z])(Rot Wallow Tusk)(?=[^A-Za-z]|$)/gi, '$1腐败兽獠牙');
data=data.replace(/(^|[^A-Za-z])(Elona Reach)(?=[^A-Za-z]|$)/gi, '$1伊洛那流域');
data=data.replace(/(^|[^A-Za-z])(Diviner's Ascent)(?=[^A-Za-z]|$)/gi, '$1预言者之坡');
data=data.replace(/(^|[^A-Za-z])(Sand Drake)(?=[^A-Za-z]|$)/gi, '$1沙龙兽');
data=data.replace(/(^|[^A-Za-z])(Topaz Crest)(?=[^A-Za-z]|$)/gi, '$1黄宝石颈脊');
data=data.replace(/(^|[^A-Za-z])(Rata Sum)(?=[^A-Za-z]|$)/gi, '$1洛达顶点');
data=data.replace(/(^|[^A-Za-z])(Magus Stones)(?=[^A-Za-z]|$)/gi, '$1玛古斯之石');
data=data.replace(/(^|[^A-Za-z])(Lifeweaver)(?=[^A-Za-z]|$)/gi, '$1织命者');
data=data.replace(/(^|[^A-Za-z])(Bloodweaver)(?=[^A-Za-z]|$)/gi, '$1织血者');
data=data.replace(/(^|[^A-Za-z])(Venomweaver)(?=[^A-Za-z]|$)/gi, '$1织恨者');
data=data.replace(/(^|[^A-Za-z])(Spider)(?=[^A-Za-z]|$)/gi, '$1蜘蛛');
data=data.replace(/(^|[^A-Za-z])(Weaver Leg)(?=[^A-Za-z]|$)/gi, '$1编织者的腿');
data=data.replace(/(^|[^A-Za-z])(Yahnur Market)(?=[^A-Za-z]|$)/gi, '$1雅诺尔市集');
data=data.replace(/(^|[^A-Za-z])(Vehtendi Valley)(?=[^A-Za-z]|$)/gi, '$1巍天帝峡谷');
data=data.replace(/(^|[^A-Za-z])(Storm Jacaranda)(?=[^A-Za-z]|$)/gi, '$1暴风荆棘');
data=data.replace(/(^|[^A-Za-z])(Mirage Iboga)(?=[^A-Za-z]|$)/gi, '$1幻象伊波枷');
data=data.replace(/(^|[^A-Za-z])(Enchanted Brambles)(?=[^A-Za-z]|$)/gi, '$1魔法树根');
data=data.replace(/(^|[^A-Za-z])(Whistling Thornbrush)(?=[^A-Za-z]|$)/gi, '$1荆棘之藤');
data=data.replace(/(^|[^A-Za-z])(Sentient Spore)(?=[^A-Za-z]|$)/gi, '$1知觉孢子');
data=data.replace(/(^|[^A-Za-z])(Ahoj)(?=[^A-Za-z]|$)/gi, '$1亚禾');
data=data.replace(/(^|[^A-Za-z])(Bottle of Vabbian Wine)(?=[^A-Za-z]|$)/gi, '$1瓦贝红酒');
data=data.replace(/(^|[^A-Za-z])(Jarimiya the Unmerciful)(?=[^A-Za-z]|$)/gi, '$1残酷 贾米里');
data=data.replace(/(^|[^A-Za-z])(Blacktide Den)(?=[^A-Za-z]|$)/gi, '$1黑潮之穴');
data=data.replace(/(^|[^A-Za-z])(Lahtenda Bog)(?=[^A-Za-z]|$)/gi, '$1洛天帝沼泽');
data=data.replace(/(^|[^A-Za-z])(Mandragor Imp)(?=[^A-Za-z]|$)/gi, '$1曼陀罗恶魔');
data=data.replace(/(^|[^A-Za-z])(Mandragor Slither)(?=[^A-Za-z]|$)/gi, '$1曼陀罗之藤');
data=data.replace(/(^|[^A-Za-z])(Stoneflesh Mandragor)(?=[^A-Za-z]|$)/gi, '$1曼陀罗石根');
data=data.replace(/(^|[^A-Za-z])(Mandragor Swamproot)(?=[^A-Za-z]|$)/gi, '$1曼陀罗根');
data=data.replace(/(^|[^A-Za-z])(Vasburg Armory)(?=[^A-Za-z]|$)/gi, '$1维思柏兵营');
data=data.replace(/(^|[^A-Za-z])(The Eternal Grove)(?=[^A-Za-z]|$)/gi, '$1永恒之林');
data=data.replace(/(^|[^A-Za-z])(Skill Hungry Gaki)(?=[^A-Za-z]|$)/gi, '$1灵巧的饿鬼');
data=data.replace(/(^|[^A-Za-z])(Pain Hungry Gaki)(?=[^A-Za-z]|$)/gi, '$1痛苦的饿鬼');
data=data.replace(/(^|[^A-Za-z])(Quarrel Falls)(?=[^A-Za-z]|$)/gi, '$1怨言瀑布');
data=data.replace(/(^|[^A-Za-z])(Silverwood)(?=[^A-Za-z]|$)/gi, '$1银树');
data=data.replace(/(^|[^A-Za-z])(Maguuma Warrior)(?=[^A-Za-z]|$)/gi, '$1梅古玛战士');
data=data.replace(/(^|[^A-Za-z])(Maguuma Hunter)(?=[^A-Za-z]|$)/gi, '$1梅古玛猎人');
data=data.replace(/(^|[^A-Za-z])(Maguuma Protector)(?=[^A-Za-z]|$)/gi, '$1梅古玛守护者');
data=data.replace(/(^|[^A-Za-z])(Maguuma Mane)(?=[^A-Za-z]|$)/gi, '$1梅古玛鬃毛');
data=data.replace(/(^|[^A-Za-z])(Seeker's Passage)(?=[^A-Za-z]|$)/gi, '$1探索者通道');
data=data.replace(/(^|[^A-Za-z])(Salt Flats)(?=[^A-Za-z]|$)/gi, '$1盐滩');
data=data.replace(/(^|[^A-Za-z])(The Amnoon Oasis)(?=[^A-Za-z]|$)/gi, '$1安努绿洲');
data=data.replace(/(^|[^A-Za-z])(Prophet's Path)(?=[^A-Za-z]|$)/gi, '$1先知之路');
data=data.replace(/(^|[^A-Za-z])(Jade Scarab)(?=[^A-Za-z]|$)/gi, '$1翡翠圣甲虫');
data=data.replace(/(^|[^A-Za-z])(Jade Mandible)(?=[^A-Za-z]|$)/gi, '$1翡翠下颚骨');
data=data.replace(/(^|[^A-Za-z])(Temple of the Ages)(?=[^A-Za-z]|$)/gi, '$1辛库走廊');
data=data.replace(/(^|[^A-Za-z])(Sunjiang District)(?=[^A-Za-z]|$)/gi, '$1孙江行政区');
data=data.replace(/(^|[^A-Za-z])(Sunjiang District)(?=[^A-Za-z]|$)/gi, '$1孙江行政区主线');
data=data.replace(/(^|[^A-Za-z])(Shenzun Tunnels)(?=[^A-Za-z]|$)/gi, '$1申赞通道');
data=data.replace(/(^|[^A-Za-z])(Afflicted)(?=[^A-Za-z]|$)/gi, '$1被感染的');
data=data.replace(/(^|[^A-Za-z])(Putrid Cyst)(?=[^A-Za-z]|$)/gi, '$1腐败胞囊');
data=data.replace(/(^|[^A-Za-z])(The Astralarium)(?=[^A-Za-z]|$)/gi, '$1世纪神殿');
data=data.replace(/(^|[^A-Za-z])(Zehlon Reach)(?=[^A-Za-z]|$)/gi, '$1黑色帷幕');
data=data.replace(/(^|[^A-Za-z])(Beknur Harbor)(?=[^A-Za-z]|$)/gi, '$1突马克荒地');
data=data.replace(/(^|[^A-Za-z])(Skale Blighter)(?=[^A-Za-z]|$)/gi, '$1森林牛头怪');
data=data.replace(/(^|[^A-Za-z])(Skale Fin)(?=[^A-Za-z]|$)/gi, '$1森林牛头怪的角');
data=data.replace(/(^|[^A-Za-z])(The Astralarium)(?=[^A-Za-z]|$)/gi, '$1亚斯特拉利姆');
data=data.replace(/(^|[^A-Za-z])(Zehlon Reach)(?=[^A-Za-z]|$)/gi, '$1列隆流域');
data=data.replace(/(^|[^A-Za-z])(Beknur Harbor)(?=[^A-Za-z]|$)/gi, '$1别克诺港');
data=data.replace(/(^|[^A-Za-z])(Issnur Isles)(?=[^A-Za-z]|$)/gi, '$1伊斯诺岛');
data=data.replace(/(^|[^A-Za-z])(Skale Blighter)(?=[^A-Za-z]|$)/gi, '$1黑暗鳞怪');
data=data.replace(/(^|[^A-Za-z])(Frigid Skale)(?=[^A-Za-z]|$)/gi, '$1寒冰鳞怪');
data=data.replace(/(^|[^A-Za-z])(Ridgeback Skale)(?=[^A-Za-z]|$)/gi, '$1脊背鳞怪');
data=data.replace(/(^|[^A-Za-z])(Skale Fin)(?=[^A-Za-z]|$)/gi, '$1鳞怪鳍');
data=data.replace(/(^|[^A-Za-z])(Chef Panjoh)(?=[^A-Za-z]|$)/gi, '$1大厨 潘乔');
data=data.replace(/(^|[^A-Za-z])(Bowl of Skalefin Soup)(?=[^A-Za-z]|$)/gi, '$1鳞怪鳍汤');
data=data.replace(/(^|[^A-Za-z])(Sage Lands)(?=[^A-Za-z]|$)/gi, '$1荒原');
data=data.replace(/(^|[^A-Za-z])(Mamnoon Lagoon)(?=[^A-Za-z]|$)/gi, '$1玛奴泻湖');
data=data.replace(/(^|[^A-Za-z])(Henge of Denravi)(?=[^A-Za-z]|$)/gi, '$1丹拉维圣地');
data=data.replace(/(^|[^A-Za-z])(Tangle Root)(?=[^A-Za-z]|$)/gi, '$1纠结之根');
data=data.replace(/(^|[^A-Za-z])(Dry Top)(?=[^A-Za-z]|$)/gi, '$1干燥高地');
data=data.replace(/(^|[^A-Za-z])(Root Behe​​moth)(?=[^A-Za-z]|$)/gi, '$1根巨兽');
data=data.replace(/(^|[^A-Za-z])(Behemoth Jaw)(?=[^A-Za-z]|$)/gi, '$1巨兽颚');
data=data.replace(/(^|[^A-Za-z])(Brauer Academy)(?=[^A-Za-z]|$)/gi, '$1袭哈拉');
data=data.replace(/(^|[^A-Za-z])(Jaga Moraine)(?=[^A-Za-z]|$)/gi, '$1亚加摩瑞恩');
data=data.replace(/(^|[^A-Za-z])(Undergrowth)(?=[^A-Za-z]|$)/gi, '$1海冶克狂战士');
data=data.replace(/(^|[^A-Za-z])(Dragon Moss)(?=[^A-Za-z]|$)/gi, '$1牛头怪狂战士');
data=data.replace(/(^|[^A-Za-z])(Dragon Moss)(?=[^A-Za-z]|$)/gi, '$1狂战士 纹帝哥');
data=data.replace(/(^|[^A-Za-z])(Dragon Moss)(?=[^A-Za-z]|$)/gi, '$1棘狼狂战士');
data=data.replace(/(^|[^A-Za-z])(Berserker Horn)(?=[^A-Za-z]|$)/gi, '$1狂战士的角');
data=data.replace(/(^|[^A-Za-z])(Brauer Academy)(?=[^A-Za-z]|$)/gi, '$1巴尔学院');
data=data.replace(/(^|[^A-Za-z])(Drazach Thicket)(?=[^A-Za-z]|$)/gi, '$1德瑞扎灌木林');
data=data.replace(/(^|[^A-Za-z])(Tanglewood Copse)(?=[^A-Za-z]|$)/gi, '$1谭格坞树林');
data=data.replace(/(^|[^A-Za-z])(Pongmei Valley)(?=[^A-Za-z]|$)/gi, '$1朋美谷');
data=data.replace(/(^|[^A-Za-z])(Undergrowth)(?=[^A-Za-z]|$)/gi, '$1矮树丛');
data=data.replace(/(^|[^A-Za-z])(Dragon Moss)(?=[^A-Za-z]|$)/gi, '$1龙苔');
data=data.replace(/(^|[^A-Za-z])(Dragon Root)(?=[^A-Za-z]|$)/gi, '$1龙根');
data=data.replace(/(^|[^A-Za-z])(Fishermen's Haven)(?=[^A-Za-z]|$)/gi, '$1渔人避风港');
data=data.replace(/(^|[^A-Za-z])(Stingray Strand)(?=[^A-Za-z]|$)/gi, '$1魟鱼湖滨');
data=data.replace(/(^|[^A-Za-z])(Tears of the Fallen)(?=[^A-Za-z]|$)/gi, '$1战死者之泪');
data=data.replace(/(^|[^A-Za-z])(Grand Drake)(?=[^A-Za-z]|$)/gi, '$1强龙兽');
data=data.replace(/(^|[^A-Za-z])(Sanctum Cay)(?=[^A-Za-z]|$)/gi, '$1神圣沙滩主线');
data=data.replace(/(^|[^A-Za-z])(Lightning Drake)(?=[^A-Za-z]|$)/gi, '$1闪光龙兽');
data=data.replace(/(^|[^A-Za-z])(Spiked Crest)(?=[^A-Za-z]|$)/gi, '$1尖刺的颈脊');
data=data.replace(/(^|[^A-Za-z])(Imperial Sanctum)(?=[^A-Za-z]|$)/gi, '$1帝国圣所');
data=data.replace(/(^|[^A-Za-z])(Raisu Palace)(?=[^A-Za-z]|$)/gi, '$1莱苏皇宫');
data=data.replace(/(^|[^A-Za-z])(Shiro'k​​en)(?=[^A-Za-z]|$)/gi, '$1白影军团');
data=data.replace(/(^|[^A-Za-z])(Soul Stone)(?=[^A-Za-z]|$)/gi, '$1灵魂石');
data=data.replace(/(^|[^A-Za-z])(Tihark Orchard)(?=[^A-Za-z]|$)/gi, '$1提亚克林地');
data=data.replace(/(^|[^A-Za-z])(Forum Highlands)(?=[^A-Za-z]|$)/gi, '$1高地广场');
data=data.replace(/(^|[^A-Za-z])(Skree)(?=[^A-Za-z]|$)/gi, '$1鸟妖');
data=data.replace(/(^|[^A-Za-z])(Skree Wing)(?=[^A-Za-z]|$)/gi, '$1鸟妖翅膀');
data=data.replace(/(^|[^A-Za-z])(Serenity Temple)(?=[^A-Za-z]|$)/gi, '$1宁静神殿');
data=data.replace(/(^|[^A-Za-z])(Pockmark Flats)(?=[^A-Za-z]|$)/gi, '$1麻点平原');
data=data.replace(/(^|[^A-Za-z])(Storm Rider)(?=[^A-Za-z]|$)/gi, '$1暴风驾驭者');
data=data.replace(/(^|[^A-Za-z])(Stormy Eye)(?=[^A-Za-z]|$)/gi, '$1暴风之眼');
data=data.replace(/(^|[^A-Za-z])(Gates of Kryta)(?=[^A-Za-z]|$)/gi, '$1科瑞塔之门');
data=data.replace(/(^|[^A-Za-z])(Scoundrel's Rise)(?=[^A-Za-z]|$)/gi, '$1恶汉山丘');
data=data.replace(/(^|[^A-Za-z])(Griffon's Mouth)(?=[^A-Za-z]|$)/gi, '$1狮鹭兽隘口');
data=data.replace(/(^|[^A-Za-z])(Spiritwood Plank)(?=[^A-Za-z]|$)/gi, '$1心灵之板');
data=data.replace(/(^|[^A-Za-z])(Tsumei Village)(?=[^A-Za-z]|$)/gi, '$1苏梅村');
data=data.replace(/(^|[^A-Za-z])(Panjiang Peninsula)(?=[^A-Za-z]|$)/gi, '$1班让半岛');
data=data.replace(/(^|[^A-Za-z])(Naga)(?=[^A-Za-z]|$)/gi, '$1纳迦');
data=data.replace(/(^|[^A-Za-z])(Naga Hide)(?=[^A-Za-z]|$)/gi, '$1纳迦皮');
data=data.replace(/(^|[^A-Za-z])(Sifhalla)(?=[^A-Za-z]|$)/gi, '$1袭哈拉');
data=data.replace(/(^|[^A-Za-z])(Drakkar Lake)(?=[^A-Za-z]|$)/gi, '$1卓卡湖');
data=data.replace(/(^|[^A-Za-z])(Frozen Elemental)(?=[^A-Za-z]|$)/gi, '$1冰元素');
data=data.replace(/(^|[^A-Za-z])(Pile of Elemental Dust)(?=[^A-Za-z]|$)/gi, '$1元素之土');
data=data.replace(/(^|[^A-Za-z])(Bergen Hot Springs)(?=[^A-Za-z]|$)/gi, '$1卑尔根温泉');
data=data.replace(/(^|[^A-Za-z])(Nebo Terrace)(?=[^A-Za-z]|$)/gi, '$1尼伯山丘');
data=data.replace(/(^|[^A-Za-z])(North Kryta Province)(?=[^A-Za-z]|$)/gi, '$1柯瑞塔北部');
data=data.replace(/(^|[^A-Za-z])(Gypsie Ettin)(?=[^A-Za-z]|$)/gi, '$1流浪双头巨人');
data=data.replace(/(^|[^A-Za-z])(Hardened Hump)(?=[^A-Za-z]|$)/gi, '$1硬瘤');
data=data.replace(/(^|[^A-Za-z])(Leviathan Pits)(?=[^A-Za-z]|$)/gi, '$1利拜亚森矿场');
data=data.replace(/(^|[^A-Za-z])(Silent Surf)(?=[^A-Za-z]|$)/gi, '$1寂静之浪');
data=data.replace(/(^|[^A-Za-z])(Seafarer's Rest)(?=[^A-Za-z]|$)/gi, '$1航海者休憩处');
data=data.replace(/(^|[^A-Za-z])(Oni)(?=[^A-Za-z]|$)/gi, '$1鬼');
data=data.replace(/(^|[^A-Za-z])(Keen Oni Talon)(?=[^A-Za-z]|$)/gi, '$1锐利细鬼爪');
data=data.replace(/(^|[^A-Za-z])(Ice Caves of Sorrow)(?=[^A-Za-z]|$)/gi, '$1悲伤冰谷');
data=data.replace(/(^|[^A-Za-z])(Icedome)(?=[^A-Za-z]|$)/gi, '$1冰点');
data=data.replace(/(^|[^A-Za-z])(Ice Elemental)(?=[^A-Za-z]|$)/gi, '$1冰元素');
data=data.replace(/(^|[^A-Za-z])(Ice Golem)(?=[^A-Za-z]|$)/gi, '$1冰高仑');
data=data.replace(/(^|[^A-Za-z])(Icy Lodestone)(?=[^A-Za-z]|$)/gi, '$1冰磁石');
data=data.replace(/(^|[^A-Za-z])(Augury Rock)(?=[^A-Za-z]|$)/gi, '$1占卜之石');
data=data.replace(/(^|[^A-Za-z])(Skyward Reach)(?=[^A-Za-z]|$)/gi, '$1天际流域');
data=data.replace(/(^|[^A-Za-z])(Destiny's Gorge)(?=[^A-Za-z]|$)/gi, '$1命运峡谷');
data=data.replace(/(^|[^A-Za-z])(Prophet's Path)(?=[^A-Za-z]|$)/gi, '$1探索者通道');
data=data.replace(/(^|[^A-Za-z])(Salt Flats)(?=[^A-Za-z]|$)/gi, '$1盐滩');
data=data.replace(/(^|[^A-Za-z])(Storm Kin)(?=[^A-Za-z]|$)/gi, '$1风暴魔');
data=data.replace(/(^|[^A-Za-z])(Shriveled Eye)(?=[^A-Za-z]|$)/gi, '$1干枯的眼睛');
